stencil-library/src/components/payment-method-form/theme.ts
Type of Change
--------------
Links
-----
=> Add missing properties to theme

.github/PULL_REQUEST_TEMPLATE.md, readme.md
Type of Change
--------------
Links
-----
=> update PR templates main README, and add changelogs

stencil-library/docs.json, stencil-library/src/components/payment-method-form/test/payment-method-form.spec.tsx
=> remove unused imports to solve warnings

stencil-library/docs.json, stencil-library/src/components/card-form/card-form.stories.ts, stencil-library/src/components/payment-form/payment-form.scss, stencil-library/src/components/payment-form/payment-form.stories.ts
=> Add payment-form styled example and fix card-form styled example

stencil-library/.storybook/preview.js, stencil-library/docs.json, stencil-library/package.json, stencil-library/src/components.d.ts, stencil-library/src/components/bank-account-form/bank-account-form.tsx, stencil-library/src/components/bank-account-form/readme.md, stencil-library/src/components/card-form/card-form.stories.ts, stencil-library/src/components/card-form/card-form.tsx, stencil-library/src/components/card-form/readme.md
=> improve docs

stencil-library/docs.json, stencil-library/src/components.d.ts, stencil-library/src/components/bank-account-form/bank-account-form.stories.ts, stencil-library/src/components/bank-account-form/bank-account-form.tsx, stencil-library/src/components/bank-account-form/readme.md
=> add stories for bank account form

stencil-library/docs.json, stencil-library/src/components/payment-form/payment-form.stories.ts
Some args weren't being passed into the 'Styled' payment form story, causing it to look wonky.
Links
-----
--------------
=> pass missing args to payment form styled story

stencil-library/docs.json, stencil-library/package.json, stencil-library/src/components.d.ts, stencil-library/src/components/billing-form/billing-form.tsx, stencil-library/src/components/billing-form/readme.md, stencil-library/storybook-pages/intro.stories.mdx
=> Add Intro to storybook

.vscode/launch.json, README.md, stencil-library/docs.json, stencil-library/package.json, stencil-library/src/api/Api.ts, stencil-library/src/components.d.ts, stencil-library/src/components/card-form/test/card-form.e2e.tsx, stencil-library/src/components/card-form/test/card-form.spec.tsx, stencil-library/src/components/payment-method-form/test/payment-method-form.e2e.tsx, stencil-library/yarn.lock
Title says it all. This change only affects components which are not released to the public yet.
=> Update Api.ts to use production api origin

stencil-library/docs.json, stencil-library/src/components/payment-method-form/payment-method-form.tsx, stencil-library/src/components/payment-method-form/test/payment-method-form.e2e.tsx, stencil-library/src/components/payment-method-form/test/payment-method-form.spec.tsx
Added unit and end-to-end tests to paymento-method-form component
--------------
=> FE-172 payment-method-form unit tests

stencil-library/src/components/bank-account-form/test/bank-account-form.e2e.tsx, stencil-library/src/components/bank-account-form/test/bank-account-form.spec.tsx
* Add unit and end-to-end tests for bank-account-form component
--------------
No QA needed
=> FE-171 bank account form unit tests

react-library/src/components/stencil-generated/index.ts, stencil-library/docs.json, stencil-library/src/components.d.ts, stencil-library/src/components/business-info/business-info-schema.ts, stencil-library/src/components/business-info/business-info.tsx, stencil-library/src/components/form/form-control-select.scss, stencil-library/src/components/form/form-control-select.tsx, stencil-library/src/components/form/form-control-text.scss, stencil-library/src/components/form/form-control-text.tsx, stencil-library/src/components/form/form-controller.ts
Create a form class to store form values, errors, and a register function for registering inputs with handlers
Links
-----
--------------
=> Form controller based forms

stencil-library/docs.json, stencil-library/src/components/bank-account-form/bank-account-form.stories.ts, stencil-library/src/components/card-form/card-form.stories.ts, stencil-library/src/components/payment-form/payment-form.stories.ts, stencil-library/storybook-pages/intro.stories.mdx
* style(stencil-library): update CSSVars in bank-account-form and card-form stories to include --jfi-form-control-box-shadow property
* style(payment-form): add box-shadow to form control and update layout padding variable value
* docs(intro.stories.mdx): add note about customizing form control box-shadow variable and layout padding value
Links
-----
--------------
- [*] Update the appropriate documentation. Keep in mind that this mono repository has README files at the repository, project, and component levels. We want …
=> FE-232 Add -jfi-form-control-box-shadow to examples 

stencil-library/docs.json, stencil-library/src/components/bank-account-form/bank-account-form.stories.ts, stencil-library/src/components/card-form/card-form.stories.ts, stencil-library/src/components/payment-form/payment-form.stories.ts, stencil-library/storybook-pages/intro.stories.mdx
- [FE-232 Add -jfi-form-control-box-shadow to examples](https://github.com/justifi-tech/web-component-library/commit/2431b8ea64f09c1be9c35476790fa9a60b25ac50)
Links
-----
--------------
=> Release 2023-06-23

stencil-library/src/components/payment-method-form/payment-method-form.tsx
The iframeOrigin was mistakenly removed. This adds it back and fallsback to IFRAME_ORIGIN env variable only if the props is not being passed. 
Links
-----
--------------
=> fix: use this.iframeOrigin if available, otherwise fallback to process.env.IFRAME_ORIGIN

.github/workflows/build_and_publish_storybook.yml, .github/workflows/create_release.yml, stencil-library/docs.json, stencil-library/package.json
It appears that in production, the `IFRAME_ORIGIN` variable is not set, causing an issue.
**Note:** It's an attempting to fix the issue. To test this in prod we could have to publish a release-candidate version.
chore(stencil-library/package.json): remove redundant build scripts and update build command
Links
-----
--------------
=> chore: update build command to include environment variables

.github/workflows/build_and_release_stencil_components.yml, stencil-library/docs.json, stencil-library/package.json
=> put back build_and_release_stencil_components.yml

.github/workflows/build_and_release_stencil_components.yml, stencil-library/docs.json, stencil-library/package.json
=> use env variable in build

stencil-library/src/components/billing-form/test/billing-form.spec.tsx, stencil-library/src/components/business-address/test/business-address.e2e.ts, stencil-library/src/components/business-address/test/business-address.spec.tsx, stencil-library/src/components/select-input/select-input.tsx, stencil-library/src/components/select-input/test/select-input.spec.tsx, stencil-library/src/components/text-input/test/text-input.spec.tsx
* (billing-form.spec.tsx): update test case descriptions and add new test cases for filling the form, validating the form, and getting form values
* (business-address.spec.tsx): update component name from 'business-address' to 'justifi-business-address'
* (business-address.spec.tsx): update component HTML to match new component name
* (business-address.spec.tsx): add test for handling 'fieldReceivedInput' event
* (business-address.spec.tsx): add test for handling form submission and validation
* (select-input.tsx): initialize options prop with an empty array
* (select-input.tsx): fix part attribute value to include 'input-invalid' class when error is present
* (select-input.spec.tsx): add tests for rendering select-input component with different props and error message
* …
=> Fix unit tests

stencil-library/src/components/card-form/card-form.tsx
=> make tests fail

.github/workflows/build_and_publish_storybook.yml
* Add back the `build_and_publish_storybook.yml` file that was deleted by mistake
Links
-----
--------------
=> fix: restore build_and_publish_storybook.yml file

stencil-library/src/components/payment-method-form/payment-method-form.tsx
* This is needed in order to set the right height for the iframe, after the [ApplyTheme has been moved](https://github.com/justifi-tech/payments-js/pull/99)
Links
-----
--------------
=> FE-253 - Refact: fix height issue

.github/workflows/build_and_release_stencil_components.yml
=> Provide 'private' and 'public' options for publishing

stencil-library/package.json, stencil-library/src/api/Api.ts, stencil-library/src/components/payments-list/payments-list.scss, stencil-library/src/components/payments-list/payments-list.stories.ts, stencil-library/src/components/payments-list/payments-list.tsx
=> [FE-268] chore: move to bootstrap styling, add PoC styled example

react-library/src/components/stencil-generated/index.ts, stencil-library/src/api/Payout.ts, stencil-library/src/components/payments-list/payments-list.scss, stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/payments-list/test/payments-list.spec.tsx, stencil-library/src/components/payouts-list/payouts-list.scss, stencil-library/src/components/payouts-list/payouts-list.tsx, stencil-library/src/components/table/table-utils.ts, stencil-library/src/components/table/table.scss, stencil-library/src/components/table/table.tsx
=> Fe 248 generic table shared components

react-library/src/components/stencil-generated/index.ts, stencil-library/src/api/Proceed.ts, stencil-library/src/components/proceeds-list/proceeds-list.scss, stencil-library/src/components/proceeds-list/proceeds-list.stories.ts, stencil-library/src/components/proceeds-list/proceeds-list.tsx
=> feat: add proceeds list component

stencil-library/src/components/payouts-list/Docs.stories.mdx, stencil-library/src/components/payouts-list/example.js, stencil-library/src/components/proceeds-list/Docs.stories.mdx, stencil-library/src/components/proceeds-list/example.js, stencil-library/src/components/table/table.tsx, stencil-library/src/components/table/test/table.spec.tsx
=> add tests to table and missing docs for list components

stencil-library/src/api/Api.ts, stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/payouts-list/payouts-list.tsx, stencil-library/src/components/proceeds-list/proceeds-list.tsx
=> Fe 307 refactor pagination in tables to abstract url formation to api ts 2

react-library/src/components/stencil-generated/index.ts, stencil-library/src/api/Api.ts, stencil-library/src/api/Business.ts, stencil-library/src/api/Payout.ts, stencil-library/src/api/Proceed.ts, stencil-library/src/api/shared.ts, stencil-library/src/components/business-list/Docs.stories.mdx, stencil-library/src/components/business-list/business-list.scss, stencil-library/src/components/business-list/business-list.stories.ts, stencil-library/src/components/business-list/business-list.tsx, stencil-library/src/components/business-list/example.js
=> feat: add business list component

stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/payouts-list/payouts-list.tsx, stencil-library/src/components/proceeds-list/proceeds-list.tsx
=> feat: add title to badges and fix some minor issues on new lists

nx.json, react-library/package.json, stencil-library/src/components/bank-account-form/readme.md, stencil-library/src/components/card-form/readme.md
- Cache result of root `test` task
- Cache result of root `test:e2e` task
- Cache result of root `build` (production build) task
- Pull this branch
- Run `npm run build`, the packages should build from scratch
- Run `npm run build` a second time without changing any code. The build should be nearly immediate, and the output should show ```✔  @justifi/webcomponents:build  [local cache]
✔  @justifi/react-components:build  [local cache]
✔  @justifi/angular-components:build  [local cache]``` as well as"Nx read the output from the cache instead of running the command for 3 out of 3 tasks."
- Change some code in one of the three workspaces and run `npm run build` yet again. The output should show that the affected workspace built and the other …
=> Lerna caching

stencil-library/src/components/business-form/additional-questions/additional-questions.tsx, stencil-library/src/components/business-form/business-form.tsx
* Added a subform with the additional questions of BusinessForm
Docs: https://developer.justifi.ai/tag/Business
```
"additional_questions": {
"business_revenue": "84220",
"business_purchase_order_volume": "150",
"business_invoice_volume": "500",
"business_fund_use_intent": "expanding marketing efforts",
"equipment_invoice": "$10,000 invoice for computer equipment",
"business_invoice_number": "202105-001",
"business_invoice_amount": "$4500",
"business_purchase_order_number": "120",
"industry_code": "541512",
"duns_number": "123456789",
"business_payment_volume": "US $1,000,000",
"business_payment_decline_volume": "500",
"business_refund_volume": "100",
"business_dispute_volume": "50",
"business_receivable_volume": "US $100,000",
"business_future_scheduled_payment_volume": "200", …
```
=> FE-183 - feat: add additional-questions section

react-library/src/components/stencil-generated/index.ts, stencil-library/package.json, stencil-library/src/api/Api.ts, stencil-library/src/components/payment-details/Docs.stories.mdx, stencil-library/src/components/payment-details/example.js, stencil-library/src/components/payment-details/payment-details.scss, stencil-library/src/components/payment-details/payment-details.stories.ts, stencil-library/src/components/payment-details/payment-details.tsx, stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/table/table.tsx, stencil-library/src/utils/utils.ts, stencil-library/storybook-pages/utils.tsx
=> feat: complete first Details component

stencil-library/src/components/payments-list/Docs.stories.mdx, stencil-library/src/components/payments-list/payments-list.stories.ts, stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/payouts-list/payouts-list.stories.ts, stencil-library/src/components/payouts-list/payouts-list.tsx, stencil-library/src/components/proceeds-list/proceeds-list.stories.ts, stencil-library/src/components/proceeds-list/proceeds-list.tsx, stencil-library/src/components/table/table.tsx
=> Fe 328 web component pattern lists emit events on row click

stencil-library/storybook-pages/angular.stories.mdx
Adds a new file `angular.stories.mdx` to the `stencil-library/storybook-pages` directory. The file contains documentation and examples for using Justifi web components with Angular.
Links
-----
--------------
=> FE-336 feat(storybook-pages): add Angular stories for Justifi web components

stencil-library/storybook-pages/angular.stories.mdx
This commit adds a new file `angular.stories.mdx` to the `stencil-library/storybook-pages` directory. The file contains documentation and examples for using Justifi web components with Angular.
The documentation includes sections on usage, usage details, and styling. It provides instructions for installing the Angular version of the web components, importing them into a module, and using them as Angular components. It also explains how to handle props names, listen to events, and call methods in Angular. Additionally, it provides information on styling the components using CSS variables and styling exported parts.
This documentation aims to help users integrate Justifi's Angular web components and provides a starting point for using them in Angular projects.
This changes were already …
=> feat(storybook-pages): add Angular stories for Justifi web components

react-library/src/components/stencil-generated/index.ts, stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/payouts-list/payouts-list.tsx, stencil-library/src/components/proceeds-list/proceeds-list.tsx, stencil-library/src/components/table/table.scss, stencil-library/src/components/table/table.tsx
=> Fe 371 improve pagination

react-library/src/components/stencil-generated/index.ts, stencil-library/src/components/business-list/Docs.stories.mdx, stencil-library/src/components/business-list/business-list.stories.ts, stencil-library/src/components/card-form/readme.md, stencil-library/src/components/payment-details/Docs.stories.mdx, stencil-library/src/components/payment-details/payment-details.stories.ts, stencil-library/src/components/payments-list/Docs.stories.mdx, stencil-library/src/components/payments-list/payments-list.stories.ts, stencil-library/src/components/payout-details/Docs.stories.mdx, stencil-library/src/components/payout-details/payout-details.stories.ts, stencil-library/src/components/payouts-list/Docs.stories.mdx, stencil-library/src/components/payouts-list/payouts-list.stories.ts, stencil-library/src/components/proceeds-list/Docs.stories.mdx, stencil-library/src/components/proceeds-list/proceeds-list.stories.ts, stencil-library/storybook-pages/react.stories.mdx
=> chore: remove dev status for new comps, fix some docs

angular-library/CHANGELOG.md, angular-library/package.json, package-lock.json, react-library/CHANGELOG.md, react-library/package.json, stencil-library/CHANGELOG.md, stencil-library/package.json, stencil-library/src/api/Api.ts, stencil-library/src/api/Payment.ts, stencil-library/src/components/payment-details/payment-details.stories.ts, stencil-library/src/components/payments-list/payments-list.stories.ts, stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/payout-details/payout-details.stories.ts, stencil-library/src/components/payouts-list/payouts-list.stories.ts, vue-library/CHANGELOG.md, vue-library/package.json
=> add: long lived read only auth

stencil-library/CHANGELOG.md, stencil-library/src/api/Business.ts, stencil-library/src/components/business-list/business-list.tsx
Fix #217 
* Use snakeCase function instead of a mapping function
* The only changes are in lines 111 and 112, as well as the removal of `mapBusinessType` and `mapBusinessStructure` methods. The rest is only indentation.
Links
-----
--------------
=> refact: use snakeCase function instead of a map

stencil-library/CHANGELOG.md, stencil-library/package.json, stencil-library/readme.md
Links
-----
Closes #247 
--------------
=> Convert readme.mdx back to readme.md

stencil-library/CHANGELOG.md, stencil-library/package.json, stencil-library/src/api/Api.ts
This fixes the error: 
`ReferenceError: process is not defined` 
Links
-----
--------------
=> fix: process undefined on browser

CONTRIBUTING.md
Still in progress at the time of this PR's creation, but I think this is a solid template to build off of. 
Links
-----
Closes #254
=> Add contributing.md doc - in progress

stencil-library/CHANGELOG.md, stencil-library/storybook-pages/vue.stories.mdx
resolves #231 
Review and update Vue Storybook documentation
Links
-----
--------------
=> docs: update Vue documentation

stencil-library/CHANGELOG.md, stencil-library/storybook-pages/react.stories.mdx
resolves #232 
Review and update React Storybook documentation.
Props, events and methods were tested in a fresh new React app.
Links
-----
--------------
=> docs: Update React documentation

stencil-library/storybook-pages/angular.stories.mdx
resolves #299
Tested in an Angular example app, and reviewed the implementation steps documentation on Storybook.
Links
-----
--------------
=> docs: review and update angular docs on storybook

stencil-library/stencil.config.ts
Links
-----
closes #272 
--------------
=> Remove sourcemap files from build

stencil-library/src/components/business-details/additional-questions-details/additional-questions-details.tsx, stencil-library/src/components/business-details/owner-details/owner-details.tsx, stencil-library/src/components/business-details/representative-details/representative-details.tsx, stencil-library/src/components/details/utils.tsx
**New screenshot after changes (display table)**
* This adds some bootstrap classes to break long texts.
* Some sections (owners and additional questions) were not being displayed because of undefined values breaking the render. This adds optional chaining to all displayed values.
* This reorganizes the Owners section to display the owner's address beside the owner's details. (Let me know what you think). Also changed the Owner section to use the Owner's Name for clarity.
**Before**
**After**
**(NOTE)** Didn't fix the problem of a long string without spaces like this:
Ideas are welcome. One would be adding `overflow: auto` to the field, so the user could side scroll to see the whole string.
Links
-----
--------------
- If this is a MAJOR version, what are the …
=> fix: text wrapping on DetailItem

stencil-library/package.json, stencil-library/readme.md
=> Improve stencil library readme

stencil-library/src/components/table/table.scss, stencil-library/src/components/table/table.tsx
Links
-----
closes #275 
--------------
=> Adjust table component responsiveness

stencil-library/src/api/Payment.ts, stencil-library/src/api/mockData/MockPayments.ts, stencil-library/src/components/payments-list/payments-list.tsx
* This adds computer payment maker name and last four digits to the Payment class
Links
-----
--------------
=> refactor: Payment class

stencil-library/src/api/Payment.ts, stencil-library/src/api/Payout.ts, stencil-library/src/components/payment-details/payment-details.tsx, stencil-library/src/components/payments-list/payments-list.tsx, stencil-library/src/components/payout-details/payout-details.tsx, stencil-library/src/components/payouts-list/payouts-list.tsx, stencil-library/src/components/subaccount-details/subaccount-details.tsx
- Removed nested ternary logic from render functions
- Ensured corrected types being used for API calls, and data is being instantiated as correct class
- made small updates to type files
- removed optional chaining `?` from some files
Links
-----
closes #286 
--------------
=> Improve payment and payout template logic

stencil-library/src/components/details/utils.tsx
=> fix: wrap detail items text

apps/docs/stories/components/payments-list.stories.tsx, apps/docs/stories/components/payouts-list.stories.tsx
=> fix: added TS ignore comment on withActions type error

stencil-library/src/components/payment-method-form/payment-method-form.tsx, stencil-library/src/components/payments-list/payments-list.tsx
* This adds a configuration object to the iframeResize call on iframe load.
* The iframeResize call seems to be not calculating the height of the iframe right.
* Strangely, adding a configuration object fixes the issue.
* There is still an issue with the inputs at the last line (bottom) of the iframe. On first load (styled form), the box-shadow is not being applied until the input has focus. I am not sure if this is related with this bug.
Links
-----
--------------
=> fix: iframe-resize malfunction

.github/PULL_REQUEST_TEMPLATE.md
This adds a small checklist for developers to review on a PR
Links
-----
--------------
=> chore: add checklist for PRs

.github/ISSUE_TEMPLATE/bug-report.md
Updates bug report template with additional info to screenshots section and new sections for code samples and videos
Links
-----
closes #350
=> Update bug report template

.changeset/hungry-starfishes-move.md, packages/webcomponents/src/components/payment-method-form/payment-method-responses.ts
I added the bin details to the type for successful card tokenize responses.  I also added specific strings for the `type` and `funding_source` properties since those are defined.  I didn't add the `card_brand` ones because it seems like we don't have all of them listed that we are supporting.
Closes #355  
Links
-----
--------------
- On any task
I used storybook to make sure that the object is coming through on the event for card-form and payment-form.
CardForm:
PaymentForm:
=> refactor(card-form):tokenize response body

apps/docs/stories/components/payment-form.stories.tsx
Links
-----
--------------
- On any task
=> adds a delay for chromatic screenshot

apps/docs/stories/components/payment-form-example.ts
I updated the Payment Form's example docs to show all of the available props and defined where to get the `client-id` and `account-id`.
Closes #362 
Links
-----
--------------
- On any task
=> Update the example for the payments form

.github/workflows/test.yaml
The tests were not executing on pull requests because the structure of the project had changed. Consequently, the path that the workflow was monitoring became outdated
Links
-----
--------------
- On any task
=> fix directory path

apps/docs/stories/components/business-form-example.ts, apps/docs/stories/components/business-form.stories.tsx
I updated the storybook documentation for the business form to show the events and also update the code example.
Links
-----
closes #375 
--------------
- On any task
=> Update business form docs

.changeset/quiet-dryers-notice.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Release 02/28/24
Updates changelog and version numbers to 4.8.1
=> Update changelog, merge changesets

.changeset/polite-bears-sneeze.md, packages/webcomponents/src/api/Business.ts, packages/webcomponents/src/components/business-form/business-form.tsx, packages/webcomponents/src/components/business-form/business-generic-info/business-generic-info.tsx, packages/webcomponents/src/components/business-form/helpers.ts, packages/webcomponents/src/components/business-form/legal-address-form/legal-address-form.tsx
Links
-----
Fixes #391 
--------------
- On any task
=> Fix country business form

packages/webcomponents/package.json, packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap, packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details.spec.tsx.snap, packages/webcomponents/src/components/payment-details/test/payment-details-core.spec.tsx, packages/webcomponents/src/components/payment-details/test/payment-details.spec.tsx, packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap, packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list.spec.tsx.snap, packages/webcomponents/src/components/payments-list/test/payments-list-core.spec.tsx, packages/webcomponents/src/components/payments-list/test/payments-list.spec.tsx, packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap, packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details.spec.tsx.snap, packages/webcomponents/src/components/payout-details/test/payout-details-core.spec.tsx, packages/webcomponents/src/components/payout-details/test/payout-details.spec.tsx, packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap, packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list.spec.tsx.snap, packages/webcomponents/src/components/payouts-list/test/payouts-list-core.spec.tsx, packages/webcomponents/src/components/payouts-list/test/payouts-list.spec.tsx
Links
-----
--------------
- On any task
=> Update test commands in package.json and enable snapshot testing

.changeset/polite-bears-sneeze.md, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
=> Release-03-06-24

packages/webcomponents/src/components/form/form-control-text.tsx, packages/webcomponents/src/components/form/test/__snapshots__/form-control-text.spec.tsx.snap, packages/webcomponents/src/components/form/test/form-control-text.spec.tsx
This adds unit tests for the `form-controller-text` component
Links
-----
--------------
- On any task
=> Add unit tests

packages/webcomponents/src/components/form/test/form.spec.ts
This adds a test suit for the FormController class
Links
-----
--------------
- On any task
=> Add FormController unit tests

.github/PULL_REQUEST_TEMPLATE.md
Links
-----
--------------
- On any task
=> Add unit tests for preventing bugs

apps/docs/.storybook/preview.ts, apps/docs/.storybook/styles.css, apps/docs/stories/changelog.stories.mdx, apps/docs/stories/components/bank-account-form-docs.stories.mdx, apps/docs/stories/components/bank-account-form.stories.tsx, apps/docs/stories/components/business-details-docs.stories.mdx, apps/docs/stories/components/business-details.stories.tsx, apps/docs/stories/components/business-form-docs.stories.mdx, apps/docs/stories/components/business-form-stepped-docs.stories.mdx, apps/docs/stories/components/business-form-stepped.stories.tsx, apps/docs/stories/components/business-form.stories.tsx, apps/docs/stories/components/card-form-docs.stories.mdx, apps/docs/stories/components/card-form.stories.tsx, apps/docs/stories/components/gross-payment-chart-docs.stories.mdx, apps/docs/stories/components/gross-payment-chart.stories.tsx, apps/docs/stories/components/payment-details-docs.stories.mdx, apps/docs/stories/components/payment-details.stories.tsx, apps/docs/stories/components/payment-form-docs.stories.mdx, apps/docs/stories/components/payment-form.stories.tsx, apps/docs/stories/components/payments-list-docs.stories.mdx, apps/docs/stories/components/payments-list.stories.tsx, apps/docs/stories/components/payout-details-docs.stories.mdx, apps/docs/stories/components/payout-details.stories.tsx, apps/docs/stories/components/payouts-list-docs.stories.mdx, apps/docs/stories/components/payouts-list.stories.tsx, apps/docs/stories/frameworks/angular.stories.mdx, apps/docs/stories/frameworks/react.stories.mdx, apps/docs/stories/frameworks/vue.stories.mdx
I am placing the stories in subdirectories.  I had to update the style sheet to put back the svg icon so that the nesting looks correct.
I needed to adjust the styling so that the sidebar nav would nest the items.  I also put the SVG back to help differentiate what level is what.
Closes #385 
Links
-----
--------------
- On any task
=> Reorganize components in sidebar

packages/webcomponents/src/components/business-form/business-representative/business-representative.tsx
--------------
- On any task
- On bugs
=> Change label from EIN/SSN to SSN

apps/docs/stories/frameworks/angular.stories.mdx, apps/docs/stories/frameworks/react.stories.mdx, apps/docs/stories/frameworks/vue.stories.mdx
I had an incorrect import path for the framework docs in storybook.  I updated it now and it should work.
Closes #410 
Links
-----
--------------
- On any task
- On bugs
=> Fixing the import paths to utils

packages/webcomponents/src/components/business-details/additional-questions-details/additional-questions-details.tsx, packages/webcomponents/src/components/business-details/generic-info-details/generic-info-details.tsx, packages/webcomponents/src/components/business-details/legal-address-details/legal-address-details.tsx, packages/webcomponents/src/components/business-details/owner-details/owner-details.tsx, packages/webcomponents/src/components/business-details/representative-details/representative-details.tsx, packages/webcomponents/src/components/details/utils.tsx, packages/webcomponents/src/components/payment-details/payment-details-core.tsx, packages/webcomponents/src/components/payment-details/payment-details.tsx, packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap, packages/webcomponents/src/components/payout-details/payout-details-core.tsx, packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap, packages/webcomponents/src/components/subaccount-details/subaccount-account-details/subaccount-account-details.tsx, packages/webcomponents/src/components/subaccount-details/subaccount-bank-details/subaccount-bank-details.tsx, packages/webcomponents/src/components/subaccount-details/subaccount-merchant-details/subaccount-merchant-details.tsx, packages/webcomponents/src/components/subaccount-details/subaccount-owners-details/subaccount-owners-details.tsx, packages/webcomponents/src/components/subaccount-details/subaccount-representative-details/subaccount-representative-details.tsx, packages/webcomponents/src/components/subaccount-details/subaccount-terms-details/subaccount-terms-details.tsx
This update modifies the `DetailSection` component to solely manage the Details Section Title. Previously, it also dictated the layout for the `DetailItem` container, which sometimes complicated alterations.
Links
-----
https://github.com/justifi-tech/web-component-library/issues/413
--------------
- On any task
=> Refact DetailSecion component

apps/docs/stories/utils/mockAllServices.ts
This adds all the routes to mock the services for all components in Storybook.
Links
-----
#437 
--------------
- On any task
[ ] - All components should be returning mock data
=> Mock all components

apps/docs/stories/components/card-form.stories.tsx, apps/docs/stories/components/payment-form.stories.tsx
This fixes the custom styles that were not being correctly applied.
It also fixes a Typescript error that was happening in this file for some time.
Links
-----
#484 
--------------
- On any task
- On bugs
[ ] - http://localhost:6006/?path=/story/payment-facilitation-payments-payment-form--styled Should render the Payment Form with the custom styles applied
[ ] - (Forcing an error) - Fill the form with a ZIP code longer then 5 digits. Submit it. An error event should be logged in the actions tab.
=> Fix decorator

.changeset/ten-berries-invite.md, packages/webcomponents/src/api/Identity.ts
Links
-----
Closes #502 
--------------
- On any task
=> Fix ssn submission bug

.changeset/olive-beers-push.md, .changeset/ten-berries-invite.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Commit changeset version

.changeset/wise-parrots-appear.md, .changeset/witty-months-refuse.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Release 05.14.24

apps/docs/stories/components/business-details.stories.tsx
This only fixes a "duplicated parameter" warning
Links
-----
--------------
- On any task
- On bugs
=> fix duplicated params warning

.github/workflows/storybook.yml, apps/docs/stories/utils/mockAllServices.ts, mockData/mockBusinessOwner.json, package.json, packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx, turbo.json
This PR makes small adjustments on mock data and turns on the mocks flag on Storybook build.
I did deploy Storybook yesterday from this branch to test and it seemed OK. 
After tested, I rolled back to `main`.
Links
-----
#533 
--------------
[ ] - All components should display mock data in Storybook
=> enable mocks on storybook prod

packages/webcomponents/src/components/insurance/insurance-state.ts, packages/webcomponents/src/components/insurance/season-interruption/season-interruption-insurance-core.tsx
Links
-----
--------------
- On any task
- On bugs
=> test stencil store

.changeset/lemon-waves-kick.md, packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step-core.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/readme.md, packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-steps.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/readme.md, packages/webcomponents/src/components/form/readme.md
- Refactors `LegalAddressFormStep` into base component and core component structure
Links
-----
Closes #611
--------------
- On any task
Ideally everything should function as it did before. This PR only changes the second form step, the legal address data, so you only need to test the second step for this PR.
=> Refactor LegalAddress form step to use core component structure

packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step-core.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/readme.md, packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-steps.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/readme.md, packages/webcomponents/src/components/form/readme.md
- Refactors `AdditionalQuestionsFormStep` into base component and core component structure
Links
-----
Closes #615 
--------------
- On any task
Ideally everything should function as it did before. This PR only changes the third form step, the additional questions data, so you only need to test the second step for this PR.
=> Refactor AdditionalQuestions form step to use core component structure 

.changeset/sixty-taxis-cough.md, packages/webcomponents/src/components/business-forms/business-form/additional-questions/additional-questions.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step.tsx
Links
-----
Closes #650 
--------------
- On any task
=> Fix label typos in additional questions

mockData/mockBusinessDetails.json, packages/webcomponents/src/components/business-details/generic-info-details/test/__snapshots__/generic-info-details.spec.tsx.snap
Links
-----
Closes #665 
--------------
- On any task
=> Update value for mock business details tax_id

.changeset/long-colts-cross.md, apps/docs/stories/utils/mockAllServices.ts, mockData/mockBusinessDetails.json, mockData/mockBusinessProvisioningSuccess.json, mockData/mockBusinessTermsSuccess.json, mockData/mockDocumentRecordSuccess.json, packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
This PR addresses some issues with PaymentProvisioning in Storybook
It commits the following changes:
- Update mock business data by adding in required data to pass default form validation
- Mock all successful API responses emitted to and from component.
- Fixes bug in document upload step where loading state is not removed if document upload request fails. 
Links
-----
Closes #671 
--------------
- On any task
- On bugs
=> Improve mock data and user experience testing provisioning form

apps/docs/stories/components/PaymentForm/Docs.mdx, apps/docs/stories/components/PaymentForm/example.ts, apps/docs/stories/components/PaymentForm/index.stories.tsx
Links
-----
--------------
- On any task
- On bugs
=> Put back PaymentForm

.github/PULL_REQUEST_TEMPLATE.md
Added a reminder for testing changes on all browsers to the PR template
Links
-----
--------------
- On any task
- On bugs
=> Update Pull request template

packages/webcomponents/src/components/business-forms/owner-form/owner-form-core.tsx, packages/webcomponents/src/components/checkout/checkout-core.tsx, packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap, packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap, packages/webcomponents/src/components/payment-form/payment-form.tsx, packages/webcomponents/src/components/payment-form/test/__snapshots__/payment-form.spec.tsx.snap, packages/webcomponents/src/styles/root.css
Links
-----
--------------
- On any task
- On bugs
=> Fix Button ui-component width

.changeset/bright-trains-wonder.md, .changeset/fluffy-spies-enjoy.md, .changeset/lemon-waves-kick.md, .changeset/long-colts-cross.md, .changeset/many-hairs-grab.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Squashes changelog files and bumps package versions ⬆️
=> 4.19.0 release

.changeset/rich-mirrors-build.md, packages/webcomponents/src/components/business-forms/utils/business-form-options.ts
Links
-----
--------------
- On any task
- On bugs
=> Update option label in business-form-options

.changeset/rich-mirrors-build.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
=> Update version number

.changeset/stale-boats-cough.md, apps/docs/stories/utils/documentation-components.tsx
- feat: add note that wct is preferred
Links
-----
--------------
- On any task
- On bugs
=> advise against static client id in card form

.changeset/friendly-poets-retire.md, .changeset/small-papayas-hear.md, .changeset/stale-boats-cough.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Release: 4.19.2

packages/webcomponents/src/components/business-details/business-details.tsx, packages/webcomponents/src/components/business-forms/business-form/business-form.tsx, packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.tsx, packages/webcomponents/src/components/checkout/checkout.tsx, packages/webcomponents/src/components/gross-payment-chart/gross-payment-chart.tsx, packages/webcomponents/src/components/insurance/season-interruption/season-interruption-insurance.tsx, packages/webcomponents/src/components/payment-details/payment-details.tsx, packages/webcomponents/src/components/payment-form/payment-form.tsx, packages/webcomponents/src/components/payments-list/payments-list.tsx, packages/webcomponents/src/components/payout-details/payout-details.tsx, packages/webcomponents/src/components/payouts-list/payouts-list.tsx, packages/webcomponents/src/utils/check-pkg-version.ts
Introduce a function to detect new major versions and log a console warning to notify users.
Links
-----
#500 
--------------
- On any task
- On bugs
[ ] - Change the package.json version to be minor than 4, then a warning message should be logged in the console.
=> Let users know when there's a new major version

apps/docs/stories/themes/dark.ts
Links
-----
--------------
- On any task
- On bugs
=> Fix input styling for dark theme

.changeset/unlucky-weeks-pay.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Bump version

.changeset/four-suns-search.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> 11.01.24 patch release

packages/webcomponents/src/api/Terminal.ts, packages/webcomponents/src/components/terminals-list/terminals-table.tsx, packages/webcomponents/src/components/terminals-list/test/__snapshots__/terminals-list-core.spec.tsx.snap
Links
-----
--------------
- On any task
- On bugs
=> Update nickname column to remove Terminal, change to just nickname

.changeset/eight-turkeys-begin.md, .changeset/purple-plants-own.md, .changeset/soft-bananas-agree.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Commit changeset version bump

.changeset/flat-students-develop.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Commit changeset

.changeset/chatty-years-clean.md, .changeset/stupid-geckos-work.md, .changeset/unlucky-crabs-doubt.md, .changeset/wild-weeks-turn.md, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json, packages/webcomponents/src/components/bank-account-form/readme.md, packages/webcomponents/src/components/card-form/readme.md
Links
-----
--------------
- On any task
- On bugs
=> Dec 16 minor release

packages/webcomponents/src/components/dispute-management/dispute-management.tsx, packages/webcomponents/src/components/dispute-management/dispute-notification.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/additional-statement.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/cancellation-policy.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/customer-details.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/dispute-response-core.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/duplicate-charge.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/electronic-evidence.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/product-or-service.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/refund-policy.tsx, packages/webcomponents/src/components/dispute-management/dispute-response/shipping-details.tsx
Links
-----
--------------
- On any task
- On bugs
=> Dispute component css parts

apps/docs/stories/themes/dark.ts, apps/docs/stories/themes/light.ts, packages/webcomponents/src/components/checkouts-list/test/__snapshots__/checkouts-list-core.spec.tsx.snap, packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap, packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap, packages/webcomponents/src/components/terminals-list/test/__snapshots__/terminals-list-core.spec.tsx.snap, packages/webcomponents/src/styles/parts.ts
Links
-----
--------------
- On any task
- On bugs
=> update font-family and color styles in dark and light themes

packages/webcomponents/src/components/tokenize-payment-method/tokenize-payment-method.tsx
Fix loading state logic: 
The loading state in this component is meant to disable the submit button while tokenizing.
Links
-----
--------------
- On any task
- On bugs
=> Fix loading state management in tokenizePaymentMethod method

apps/docs/stories/components/Checkout/Docs.mdx, apps/docs/stories/utils/documentation-components.tsx
…ut Docs
Links
-----
--------------
- On any task
- On bugs
=> Adjust spacing for ComponentBox, adjust headers and spacing in Checkout Docs

apps/component-examples/examples/payments-list-with-filters.js, packages/webcomponents/src/components/payments-list/payments-list-filters.tsx, packages/webcomponents/src/styles/parts.ts
Links
-----
--------------
- On any task
- On bugs
=> Enhance payments list filters with new parts

.changeset/hip-swans-attack.md, .changeset/tender-gifts-smell.md, .changeset/twelve-mugs-wave.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Minor-release-02-03-25

apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Patch Release 02.05.2025

.changeset/cool-oranges-repair.md, .changeset/silver-masks-confess.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Patch Release 02/07/25

packages/webcomponents/src/components/checkout/bank-account-form/bank-account-form-skeleton.tsx, packages/webcomponents/src/components/checkout/bank-account-form/bank-account-form.tsx, packages/webcomponents/src/components/checkout/card-form/card-form-skeleton.tsx, packages/webcomponents/src/components/checkout/card-form/card-form.tsx
Links
-----
--------------
- On any task
- On bugs
=> Refactor new skeletons to functional components

.changeset/odd-kiwis-guess.md, packages/webcomponents/package.json, packages/webcomponents/src/api/services/payout.service.ts, packages/webcomponents/src/components/payout-details/get-payout-csv.ts, packages/webcomponents/src/components/payout-details/payout-details.tsx
Closes #912 
--------------
- On any task
=> Pass through API origin Payout Components to CSV Download request

.changeset/odd-kiwis-guess.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Commit version bump 5.3.4

.changeset/fair-camels-peel.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Release-03-12-25

apps/component-examples/examples/order-terminals.js
Links
-----
--------------
- On any task
- On bugs
=> Remove duplicate account-id attribute in order-terminals example

.changeset/dry-falcons-tease.md, .changeset/strange-lobsters-roll.md, .changeset/witty-coins-grow.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Commit component library version bump

.changeset/smooth-boats-obey.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Release 03 18 25

.changeset/lemon-students-unite.md, .changeset/twelve-cobras-eat.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Commit version bump 5.4.3

apps/component-examples/examples/payment-details.js, apps/component-examples/examples/payout-details.js, apps/component-examples/package.json, package.json
Links
-----
#68 
--------------
- On any task
- On bugs
My current env file looks like: 
```
IFRAME_ORIGIN=https://components.justifi.ai
PROXY_API_ORIGIN=https://wc-proxy.justifi-staging.com
#Production
PORT=3420
API_ORIGIN=https://api.justifi-staging.com
AUTH_TOKEN_ENDPOINT=https://api.justifi-staging.com/oauth/token
WEB_COMPONENT_TOKEN_ENDPOINT=https://api.justifi-staging.com/v1/web_component_tokens
CHECKOUT_ENDPOINT=https://api.justifi-staging.com/v1/checkouts
BUSINESS_ENDPOINT=https://api.justifi-staging.com/v1/entities/business
SUB_ACCOUNT_ID=acc_323sM3WDAUnHH0fJD7re9h
PAYMENT_METHOD_GROUP_ID=
DISPUTE_ID=dp_2QjAGbou7enGsbkXASrjsG …
```
=> 68 example app add example files for justifi payment details and justifi payout details

apps/component-examples/examples/modular-checkout.js, apps/component-examples/package.json, package.json
**This PR includes the following updates:**
- Add example file for the modular checkout with basic configuration. 
- Add scripts needed to run the example. 
Links
-----
--------------
- On any task
=> Add modular checkout example and update scripts for development

apps/component-examples/examples/modular-checkout.js, packages/webcomponents/src/components/checkout-wrapper/checkout-wrapper.tsx, packages/webcomponents/src/components/tokenize-payment-method/tokenize-payment-method.tsx, packages/webcomponents/src/store/checkout.store.ts
POC for testing calling a tokenize from a slotted tokenize-payment-method from a slotted button. 
Links
-----
--------------
- On any task
- On bugs
=> Implement checkout wrapper component and integrate tokenization logic

.changeset/clean-worlds-ask.md, .changeset/clever-ghosts-take.md, .changeset/deep-peaches-divide.md, .changeset/dirty-phones-beam.md, .changeset/fruity-socks-smell.md, .changeset/lovely-rabbits-call.md, .changeset/mean-wings-search.md, .changeset/whole-flies-deny.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
=> Release-04-16-25

.changeset/neat-beans-agree.md, .changeset/orange-pugs-win.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Bump minor version

packages/webcomponents/src/components/checkouts-list/test/__snapshots__/checkouts-list-core.spec.tsx.snap, packages/webcomponents/src/components/payments-list/payments-list-core.tsx, packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap, packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap, packages/webcomponents/src/components/terminal-orders-list/test/__snapshots__/terminal-orders-list-core.spec.tsx.snap, packages/webcomponents/src/components/terminals-list/test/__snapshots__/terminals-list-core.spec.tsx.snap, packages/webcomponents/src/styles/parts.ts, packages/webcomponents/src/ui-components/pagination-menu/pagination-menu.tsx
Add css parts to tables / table pagination to make them more customizable:
- pagination buttons
- pagination button icons (so they can be hidden, or potentially changed using css content)
- table-row (mostly so that :hover styles can be applied!)
- spinner/loading state
Links
-----
--------------
- On any task
- On bugs
=> Add new css parts to tables to make them more customizable

.changeset/spotty-lands-ring.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json, pnpm-lock.yaml
Links
-----
--------------
- On any task
- On bugs
=> Release 05 12 25

.env.example, apps/component-examples/examples/checkout-with-insurance.js, apps/component-examples/examples/checkout.js, apps/component-examples/examples/checkouts-list-with-filters.js, apps/component-examples/examples/checkouts-list.js, apps/component-examples/examples/dispute.js, apps/component-examples/examples/order-terminals.js, apps/component-examples/examples/payment-details.js, apps/component-examples/examples/payment-provisioning.js, apps/component-examples/examples/payment-transactions-list.js, apps/component-examples/examples/payments-list-with-filters.js, apps/component-examples/examples/payments-list.js, apps/component-examples/examples/payout-details.js, apps/component-examples/examples/payout-transactions-list.js, apps/component-examples/examples/payouts-list-with-filters.js, apps/component-examples/examples/payouts-list.js, apps/component-examples/examples/refund-payment.js, apps/component-examples/examples/terminal-orders-list-with-filters.js, apps/component-examples/examples/terminal-orders-list.js, apps/component-examples/examples/terminals-list-with-filters.js, apps/component-examples/examples/terminals-list.js, apps/component-examples/examples/tokenize-payment-method.js, apps/component-examples/utils/api-paths.js
**Delete `**ENDPOINT` variables from the .env file**
In order to simplify our `.env` file.
Links
-----
https://github.com/justifi-tech/engineering-artifacts/issues/390
=> Refactor API endpoint handling and add API_PATHS utility module

.changeset/bright-baboons-melt.md, mockData/mockPaymentDetailSuccess.json, mockData/mockPayoutDetailsSuccess.json, packages/webcomponents/src/api/Payment.ts, packages/webcomponents/src/api/Payout.ts, packages/webcomponents/src/components/payment-details/payment-details-core.tsx, packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap, packages/webcomponents/src/components/payout-details/payout-details-core.tsx, packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap
Links
-----
--------------
- On any task
- On bugs
=> Add expedited and settlement priority statuses to detail screens

.changeset/bright-baboons-melt.md, .changeset/cold-symbols-teach.md, .changeset/lucky-hats-live.md, apps/component-examples/CHANGELOG.md, apps/component-examples/package.json, apps/docs/CHANGELOG.md, apps/docs/package.json, packages/webcomponents/CHANGELOG.md, packages/webcomponents/package.json
Links
-----
--------------
- On any task
- On bugs
=> Commit version bump

apps/component-examples/examples/modular-checkout.js, packages/webcomponents/src/components/modular-checkout-parts/bank-account.tsx, packages/webcomponents/src/components/modular-checkout-parts/card-form.tsx
Links
-----
--------------
- On any task
- On bugs
=> Use config state in modular checkout parts

apps/component-examples/README.md, apps/component-examples/package.json, apps/component-examples/src/index.ts, apps/component-examples/src/jsx.d.ts, apps/component-examples/src/utils/api-paths.ts, apps/component-examples/src/utils/simple-jsx.ts, apps/component-examples/tsconfig.json, pnpm-lock.yaml
=> Add TypeScript support and examples for JustiFi web components

apps/component-examples/PLAN.md, apps/component-examples/src/components/CheckoutComponent.tsx, apps/component-examples/src/examples/checkout-example.ts, apps/component-examples/src/server/auth-service.ts, apps/component-examples/src/server/express-server.ts, apps/component-examples/src/server/jsx-renderer.ts, apps/component-examples/src/server/static-assets.ts, apps/component-examples/src/templates/base-template.tsx
**Note 1:** This task refactor just the Checkout example so we can review it and proceed with the other components in a separate PR.
**Note 2:** Checked in the `plan.md` file to help keep context for Cursor, but will be removed once all tasks are completed.
- Created `CheckoutComponent` for rendering checkout UI with props.
- Developed `checkout-example.ts` to handle checkout logic and server integration.
- Implemented `AuthService` for token management and authentication.
- Set up `ExpressServer` for handling requests and serving static assets.
- Added `JSXRendererService` for rendering JSX templates to HTML.
- Introduced `StaticAssetsService` for serving web components and styles.
- Created `base-template.tsx` for consistent HTML structure across examples.
Links
----- …
=> Examples Refactor: (Task 1.2) - Add initial implementation of checkout example with JSX support

apps/docs/stories/components/ModularCheckout/Sub-components/ApplePay/Docs.mdx, apps/docs/stories/components/ModularCheckout/Sub-components/PlaidPaymentMethod/Docs.mdx, apps/docs/stories/utils/documentation-components.tsx
This pull request updates the documentation for the Apple Pay and Plaid Payment Method sub-components in the Modular Checkout, introducing a reusable `Banner` component to highlight upcoming features and removing inline usage examples from the docs. The changes focus on improving the clarity and consistency of the documentation and providing a clear "coming soon" notice for unreleased features.
**Documentation improvements:**
* Added a reusable `Banner` component in `documentation-components.tsx` to display informational messages in documentation pages.
* Inserted a "Coming soon!" banner at the top of both the Apple Pay and Plaid Payment Method documentation pages to indicate these features are previews of upcoming versions
**Content cleanup:**
* Removed inline component usage examples …
=> Add coming soon banners to Apple Pay and Plaid

apps/docs/.storybook/preview.ts
Links
-----
https://github.com/justifi-tech/engineering-artifacts/issues/964
--------------
- On any task
- On bugs
- Run the webcomponents: `pnpm build && pnpm dev`.
- Go to `http://localhost:6006`.
=> Moved "Payment Facilitation" Storybook sidebar group to be right after "Modular Checkout".

.changeset/thick-bananas-trade.md, packages/webcomponents/CHANGELOG.md
Remove deprecated thick-bananas-trade changeset file and update changelog for justifi-modular-checkout version 6.0.0, highlighting the addition of new components for a more flexible checkout experience.
Links
-----
--------------
- On any task
- On bugs
=> Add missing changelog for v6.0.0

packages/webcomponents/.changeset/fuzzy-eggs-flow.md, packages/webcomponents/src/components/payments-list/payments-table.tsx, packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap
This pull request adds a new "Card Brand" column to the payments table in the web components package, allowing users to see the brand of the payment method (e.g., VISA, Mastercard) for each payment. It introduces a mapping function to display user-friendly brand names and updates the rendering logic and tests to support this new column.
**Payments Table Enhancements:**
* Added a new `card_brand` column to the payments table, updating both the column definitions and the cell rendering logic to show the payment method's brand using a user-friendly display name.
* Implemented the `mapCardBrandToDisplayName` function to consistently format and display card brand names based on the raw brand value. (`packages/webcomponents/src/components/payments-list/payments-table.tsx`
Links
-----
Developer …
=> feat: add brand column to Payments List
