react-library/package.json
react-library/yarn.lock

The `react-library` is generated code and does not have tests, and therefore Jest can be removed (which will reduce the number of dependabot alerts we are seeing)
Links
-----
--------------

Remove unused jest from react-library

---

stencil-library/docs.json
stencil-library/src/components.d.ts
stencil-library/src/components/bank-account-form/readme.md
stencil-library/src/components/bank-account-form/test/bank-account-form.spec.tsx
stencil-library/src/components/card-form/readme.md
stencil-library/src/components/card-form/test/card-form.spec.tsx
stencil-library/src/components/payment-method-form/payment-method-form.tsx
stencil-library/src/components/payment-method-form/readme.md
stencil-library/src/components/payment-method-form/test/payment-method-form.spec.tsx

Rename `clientKey` to `clientId`.
Solves: https://justifi-ai.atlassian.net/browse/FE-46
This change should not really break anything since the work `clientKey` is never actually used externally, just internally.
The call signature is `fn(clientKey, arg2, arg3)` so when calling it, it would always be used as `fn(<clientKey string>, arg2, arg3)`. No explicit use of the keyword `clientKey` or `clientId` (no named arguments as in an object).
Type of Change
--------------

Rename clientKey to clientId

---

react-library/package.json
react-library/src/components/stencil-generated/index.ts
react-library/yarn.lock
stencil-library/docs.json
stencil-library/src/components.d.ts
stencil-library/src/components/bank-account-form/readme.md
stencil-library/src/components/card-form/readme.md
stencil-library/src/components/payment-method-form/readme.md
stencil-library/yarn.lock

- Change version in react-library to `0.2.0` to match that of `webcomponents`.
- Update `webcomponents` dependency to latest.
- Update package `typescript` and `@types/node` to solve issues.
- Confirmed it built the react-components properly.
- Include changes to lockfile in stencil-library as well, after running install on it.

upgrade to latest version of webcomponents

---

react-library/package.json
react-library/yarn.lock

Solves https://justifi-ai.atlassian.net/browse/FE-82
Dev QA plan:
- git checkout the branch `origin / update-np-pkg`
- Run yarn install in both `stencil-library` and `react-library` just to be safe.
- `yarn build` the stencil library, then `yarn build` the react library.
- Expect everything to work and build properly (other than the known issue with `JustifiPaymentForm`)

update np package to solve dependabot alerts

---

react-library/src/components/stencil-generated/index.ts
stencil-library/docs.json
stencil-library/src/components.d.ts
stencil-library/src/components/business-address/business-address-schema.ts
stencil-library/src/components/business-address/business-address.scss
stencil-library/src/components/business-address/business-address.tsx
stencil-library/src/components/business-address/example.html
stencil-library/src/components/business-address/readme.md
stencil-library/src/components/business-address/test/business-address.e2e.ts
stencil-library/src/components/business-address/test/business-address.spec.tsx
stencil-library/src/components/select-input/readme.md
stencil-library/src/components/text-input/readme.md

Create a generic address form to be reused across business and identity components. This will not be included in storybook, it will provide value to other components and part of a larger widget. It's an internal component, so because of this it will not require a version bump, changelog entry, or docs.
- Markup the address form
- Add bootstrap styling
- Add submit method with validation
- returns `isValid`
- returns form values
Links
-----
https://justifi-ai.atlassian.net/browse/FE-185?atlOrigin=eyJpIjoiNDU0N2YwNzU4NmQ1NGNjMzlmNGRlYWQ0YmYyYzI2ZjAiLCJwIjoiaiJ9
-------------- …

Create generic business-address component

---

.vscode/launch.json
README.md
stencil-library/docs.json
stencil-library/package.json
stencil-library/src/components/card-form/test/card-form.e2e.tsx
stencil-library/src/components/card-form/test/card-form.spec.tsx
stencil-library/src/components/payment-method-form/test/payment-method-form.e2e.tsx

- adds unit tests for props and methods for the card-form web-component
- adds e2e test for the `cardFormReady` event
--------------

FE-170 add unit and e2e tests to card-form component

---

react-library/src/components/stencil-generated/index.ts
stencil-library/docs.json
stencil-library/src/components.d.ts
stencil-library/src/components/business-info/business-info-schema.ts
stencil-library/src/components/business-info/business-info.scss
stencil-library/src/components/business-info/business-info.tsx
stencil-library/src/components/business-info/example.html
stencil-library/src/components/business-info/readme.md

This creates the base business-info component which will be expanded in follow-up PRs and released all at once upon completion. Therfore this PR does not include a version increment, changelog update, or documentation / storybook stories
Links
-----
--------------
The business info component will receive full QA prior to release

FE-182: Add business-info component

---

stencil-library/.storybook/preview.jsx
stencil-library/docs.json
stencil-library/storybook-pages/css-variables.tsx
stencil-library/storybook-pages/intro.stories.mdx
stencil-library/storybook-pages/react.stories.mdx
stencil-library/storybook-pages/utils.tsx

Changes:
- Add a React page to docs.
- Include necessary details on usage for the React version of the components.
- Abstract away the CSS variables list to avoid duplicating code.
- Add a new Summary component to allow showing/hiding some content.
- Fix a few links to components from intro and react page in the styling with css variables section.
Solves:
- https://justifi-ai.atlassian.net/browse/FE-161
- https://justifi-ai.atlassian.net/browse/FE-162
Screenshots:

[FE-161][FE-162] improve some docs and add React page

---

README.md
stencil-library/src/components/bank-account-form/Docs.stories.mdx
stencil-library/src/components/billing-form/Docs.stories.mdx
stencil-library/src/components/card-form/Docs.stories.mdx

This PR adds a disclaimer that tells the user that we recommend using the `PaymentForm` component - this disclaimer is added to the docs for `CardForm`, `BankAccountForm`, and `BillingForm`
Additionally, this PR updates the GH readme file to point to Storybook as our documentation for the components. 
Links
-----
Closes #242

Add disclaimers to Payment Component Docs

---

package-lock.json
stencil-library/src/components/business-form/business-form-example.js
stencil-library/src/components/business-form/business-form-stepped-example.js
stencil-library/src/components/business-form/business-form-stepped.Docs.stories.mdx
stencil-library/src/components/business-form/business-form.Docs.stories.mdx
stencil-library/src/components/gross-payment-chart/Docs.stories.mdx
stencil-library/src/components/gross-payment-chart/example.js

As the title suggests, this PR adds the correct docs.stories.mdx files for the following components: `GrossPaymentChart`, `BusinessForm`, and `BusinessFormStepped`
Also adds example js files for the `Example Usage` section for each component
Links
-----
Closes #288 
Closes #289 
--------------

Add docs.stories.mdx to GrossPaymentChart, and BusinessForm components

---

.changeset/gentle-pots-whisper.md
packages/webcomponents/src/api/BusinessV2.ts
packages/webcomponents/src/components/business-form/legal-address-form/legal-address-form.tsx

The `BusinessForm` requires a `business-id` for an existing business, which it will then load and pre-fill the form. However, when the form is pre-filled, the country is not being set.
This causes the form to not submit because country is required, disabled (because we only support USA as of now)  and has no value.
We should leave the validator and the disabled state and make sure the value of the select is set to the country saved in the loaded business, or defaults to "United States"
--------------
- On any task
- Run the branch locally
- In Storybook go to "BusinessForm"

BusinessForm "Country" input is disabled, required, and does not have a value

---

.changeset/poor-moose-smash.md
packages/webcomponents/src/api/BusinessV2.ts
packages/webcomponents/src/components/business-form/business-generic-info/business-generic-info.tsx

Core business information was not populating in the form when the business is loaded. This is because the form values were not being subscribed to in the `GenericBusinessInfo` sub form component.
--------------
- On any task
- Run the branch locally

Prefill business generic info

---

apps/docs/stories/utils/code-examples.ts

This adds the link for the styles to all the storybook examples
(I noticed there are 2 script tags in the head: `webcomponents.js` and `webcomponents.esm.js`, is it alright?)
Links
-----
--------------
- On any task

fix: style link was missing in examples

---

packages/webcomponents/src/components/bank-account-form/bank-account-form.tsx
packages/webcomponents/src/components/bank-account-form/test/bank-account-form.spec.tsx
packages/webcomponents/src/components/card-form/card-form.tsx
packages/webcomponents/src/components/card-form/test/card-form.spec.tsx

This adds a default `iframe-origin` prop value from the config file to `card-form` and `bank-account-form`. 
Links
-----
--------------
- On any task

Add default iframe-origin to bank-account-form and card-form components

---

packages/webcomponents/src/components/form/form-control-datepart.tsx
packages/webcomponents/src/components/form/test/__snapshots__/form-control-datepart.spec.tsx.snap
packages/webcomponents/src/components/form/test/form-control-datepart.spec.tsx

This adds unit tests to the `form-control-datepart` component
Links
-----
https://github.com/justifi-tech/web-component-library/issues/322
--------------
- On any task

Add form-control-datepart unit tests

---

packages/webcomponents/src/components/form/form-control-monetary.tsx
packages/webcomponents/src/components/form/test/__snapshots__/form-control-monetary.spec.tsx.snap
packages/webcomponents/src/components/form/test/form-control-monetary.spec.tsx

This adds unit tests to the `form-control-monetary` component.
Links
-----
https://github.com/justifi-tech/web-component-library/issues/322
--------------
- On any task

Add form-control-monetary unit-tests

---

packages/webcomponents/src/components/form/form-control-number.tsx
packages/webcomponents/src/components/form/test/__snapshots__/form-control-number.spec.tsx.snap
packages/webcomponents/src/components/form/test/form-control-number.spec.tsx

This adds some unit tests to the form-control-number component
Links
-----
https://github.com/justifi-tech/web-component-library/issues/322
--------------
- On any task

Add form-control-number unit tests

---

apps/docs/stories/components/payments-list-example.ts
apps/docs/stories/components/payments-list.stories.tsx
packages/webcomponents/src/api/Api.ts
packages/webcomponents/src/components/payments-list/payments-list-core.tsx
packages/webcomponents/src/components/payments-list/payments-list.tsx
packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list.spec.tsx.snap
packages/webcomponents/src/components/payments-list/test/payments-list-core.spec.tsx
packages/webcomponents/src/components/payments-list/test/payments-list.spec.tsx

This adds the expiredToken event to the `justifi-payments-lis` component.
It's emitted when `payments-list-core` emits error-event with the error "Not Authenticated`.
Also added the `row-clicked` event to the Storybook actions tab
Links
-----
https://github.com/justifi-tech/web-component-library/issues/424
--------------
- On any task
Expired token: `eyJraWQiOiJqdXN0aWZpLTQxNTczZmIyNjU0MDVmNDY0Y2UyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguanVzdGlmaS1zdGFnaW5nLmNvbS8iLCJhenAiOiJ3Y3RfNVNKckZPWTI0YXJ5bUJRc2xTY3hvRiIsInN1YiI6IndjdF81U0pyRk9ZMjRhcnltQlFzbFNjeG9GQHNlc3Npb25zIiwiYXVkIjoiaHR0cHM6Ly9hcGkuanVzdGlmaS5haS92MSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbIndyaXRlOmFjY …

add tokenExpired event to payments list

---

apps/docs/stories/components/payout-details-example.ts
apps/docs/stories/components/payout-details.stories.tsx
packages/webcomponents/src/api/Api.ts
packages/webcomponents/src/components/payout-details/get-payout-details.ts
packages/webcomponents/src/components/payout-details/payout-details-core.tsx
packages/webcomponents/src/components/payout-details/payout-details.tsx
packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap
packages/webcomponents/src/components/payout-details/test/get-payout-details.spec.ts
packages/webcomponents/src/components/payout-details/test/payout-details-core.spec.tsx
packages/webcomponents/src/components/payout-details/test/payout-details.spec.tsx

This adds the expiredToken event to the `justifi-payout-details` component.
It's emitted when `payout-details-core` emits error-event with the error "Not Authenticated`.
Links
-----
https://github.com/justifi-tech/web-component-library/issues/424
--------------
- On any task
Expired token: `eyJraWQiOiJqdXN0aWZpLTQxNTczZmIyNjU0MDVmNDY0Y2UyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguanVzdGlmaS1zdGFnaW5nLmNvbS8iLCJhenAiOiJ3Y3RfNVNKckZPWTI0YXJ5bUJRc2xTY3hvRiIsInN1YiI6IndjdF81U0pyRk9ZMjRhcnltQlFzbFNjeG9GQHNlc3Npb25zIiwiYXVkIjoiaHR0cHM6Ly9hcGkuanVzdGlmaS5haS92MSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbIndyaXRlOmFjY291bnQ6YWNjXzMzTzlESWdJZVMzOTFMSUxIRVIxZmYiLCJ3cml0ZTpidXNpbm …

add tokenExpired event to payout details

---

apps/docs/stories/components/payouts-list-example.ts
apps/docs/stories/components/payouts-list.stories.tsx
packages/webcomponents/src/api/Api.ts
packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
packages/webcomponents/src/components/payouts-list/payouts-list.tsx
packages/webcomponents/src/components/payouts-list/test/payouts-list-core.spec.tsx
packages/webcomponents/src/components/payouts-list/test/payouts-list.spec.tsx

This adds the expiredToken event to the `justifi-payouts-lis` component.
It's emitted when `payouts-list-core` emits error-event with the error "Not Authenticated`.
Also added the `row-clicked` event to the Storybook actions tab
Links
-----
https://github.com/justifi-tech/web-component-library/issues/424
--------------
- On any task
Expired token: `eyJraWQiOiJqdXN0aWZpLTQxNTczZmIyNjU0MDVmNDY0Y2UyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguanVzdGlmaS1zdGFnaW5nLmNvbS8iLCJhenAiOiJ3Y3RfNVNKckZPWTI0YXJ5bUJRc2xTY3hvRiIsInN1YiI6IndjdF81U0pyRk9ZMjRhcnltQlFzbFNjeG9GQHNlc3Npb25zIiwiYXVkIjoiaHR0cHM6Ly9hcGkuanVzdGlmaS5haS92MSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyIsInBlcm1pc3Npb25zIjpbIndyaXRlOmFjY29 …

add tokenExpired event to payouts list

---

packages/webcomponents/src/api/Business.ts
packages/webcomponents/src/api/Identity.ts
packages/webcomponents/src/components/business-details/owner-details/owner-details.tsx
packages/webcomponents/src/components/business-details/representative-details/representative-details.tsx
packages/webcomponents/src/components/business-forms/business-form-stepped/business-form-stepped.tsx
packages/webcomponents/src/components/business-forms/business-form-stepped/business-owners/business-owners-form-step.tsx
packages/webcomponents/src/components/business-forms/business-form-stepped/legal-address-form/legal-address-form-step.tsx
packages/webcomponents/src/components/business-forms/owner-form/owner-form.scss
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
packages/webcomponents/src/components/business-forms/utils/payload-parsers.ts
packages/webcomponents/src/components/form/form.ts

This PR re-implements the owners form into `business-form-stepped`. 
Some other small updates worth mentioning:
- Created Identity type file and abstracted identity / owner / representative things out of Business.ts and into Identity.ts
- Removed `private` from form.ts validate method so it could be used independently in owner-form
Links
-----
Closes #405 
--------------
- On any task
We will want to test the owners section of the business form excessively. 
In order to test, you should be comfortable using insomnia to create businesses, patch existing businesses, create web component tokens, etc.
In the case that you are going through the form with a newly created business that has no owner data:
- [

Implement new identity form into business form

---

apps/docs/.storybook/main.ts
apps/docs/globals.d.ts
apps/docs/package.json
apps/docs/stories/utils/decorators.ts
apps/docs/stories/utils/mockAllServices.ts
package.json
pnpm-lock.yaml

This PR introduces a straightforward approach for integrating mock data within our Storybook setup. It revolves around a new environment variable, `VITE_STORYBOOK_MOCKS_ENABLED`, which can be toggled between true and false within the pnpm dev script.
Setting `VITE_STORYBOOK_MOCKS_ENABLED` to true activates the `createServer()` function from [MirageJS](https://miragejs.com/), enabling us to define custom responses for API calls within the global story decorator. 
This feature provides flexibility in running or building Storybook by either connecting to our proxy API or utilizing the mock data, ensuring a seamless workflow. Additionally, this setup is configured to support Chromatic visual testing using the mocked data build.
**TODO in upcoming PRs**:
- Relocate all mock JSON responses to a …

adds mockdata to the business-details in storybook

---

.github/workflows/chromatic-deployment.yaml
apps/docs/.storybook/main.ts
apps/docs/chromatic.config.json
apps/docs/globals.d.ts
apps/docs/package.json
apps/docs/stories/utils/decorators.ts
apps/docs/stories/utils/mockAllServices.ts

* This adds back the Chromatic workflow
* Also make Gross Payment Chart load proxyAPI data on Storybook, and mock data in Chromatic
Links
-----
#437 
--------------
- On any task

feat: enable Chromatic workflow

---

apps/docs/stories/components/payouts-list.stories.tsx
packages/webcomponents/src/api/ComponentError.ts
packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
packages/webcomponents/src/components/payouts-list/payouts-list.tsx
packages/webcomponents/src/components/payouts-list/readme.md
packages/webcomponents/src/components/payouts-list/test/payouts-list-core.spec.tsx
packages/webcomponents/src/components/payouts-list/test/payouts-list.spec.tsx

This adds an `errorEvent` to the PayoutsList that can be listened to handle errors.
Also creates a `componentError` type to be used across components.
Links
-----
#433 
--------------
- On any task
[ ] - If an API error happens or If `authToken` or `accountId` are removed, it should emit `errorEvent` with the error details.
It the event should be logged in the Storybook actions tab

Adds errorEvent to Payouts list

---

packages/webcomponents/src/api/Business.ts
packages/webcomponents/src/components/business-details/additional-questions-details/additional-questions-details.tsx
packages/webcomponents/src/components/business-forms/business-form-stepped/additional-questions/business-additional-questions-form-step.tsx
packages/webcomponents/src/components/business-forms/business-form-stepped/business-representative/business-representative-form-step.tsx

This PR fixes an issue reported during our QA review last week. One of our participants noted that they got to the Representative step of the form and were unable to trigger validation by clicking Next or Previous buttons. After investigating briefly, I saw that the data that was being supplied to the form controller at this point was `null`, and it doesn't know how to trigger validation on `null`. 
This PR fixes this issue for both `additional-questions` and `representative` form steps by instantiating the data and ensuring there is an object supplied to the form controller for both of these steps. 
Links
-----
Closes #462 
Reference to issue on Google Sheets: [https://docs.google.com/spreadsheets/d/1KpgaPMl0X9OWxm7D3yAoBDOqkHcpTtWInZLS0OxqPSw/edit#gid=503272030&range=3:3](https://docs.go …

Instantiate classes for additional-questions and representative form steps

---

.changeset/calm-sloths-kick.md
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.tsx

A number of users during our QA review complained that they could not click the `Previous` button without completing the current form step. This PR addresses this by simply removing the `validateAndSubmit` call from `previousStepButtonOnClick`
Links
-----
resolves #453 
--------------
- On any task

PaymentProvisioning - Allow previous step without validate

---

.changeset/silver-bananas-remain.md
packages/webcomponents/src/components/business-forms/business-form/business-representative/business-representative.tsx
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx

This change is for `BusinessForm` (Representative section) and `PaymentProvisioning` (Steps 4 and 5, Rep and Owner Forms)
Links
-----
Closes #457 
--------------
- On any task
For BusinessForm:
For PaymentProvisioning:

BusinessForm and PaymentProvisioning - Update Prefix Inputs to Title Inputs

---

packages/webcomponents/src/api/ComponentError.ts
packages/webcomponents/src/api/services/utils.ts
packages/webcomponents/src/api/shared.ts
packages/webcomponents/src/components/business-details/business-details-core.tsx
packages/webcomponents/src/components/business-details/get-business.ts
packages/webcomponents/src/components/business-details/test/busines-details-core.spec.tsx
packages/webcomponents/src/components/business-details/test/get-business.spec.ts
packages/webcomponents/src/components/gross-payment-chart/get-gross-payment-chart-data.ts
packages/webcomponents/src/components/gross-payment-chart/gross-payment-chart-core.tsx
packages/webcomponents/src/components/gross-payment-chart/test/get-gross-payment-chart-data.spec.ts
packages/webcomponents/src/components/gross-payment-chart/test/gross-payment-chart-core.spec.tsx
packages/webcomponents/src/components/gross-payment-chart/test/gross-payment-chart.spec.tsx
packages/webcomponents/src/components/payment-details/get-payment-details.ts
packages/webcomponents/src/components/payment-details/payment-details-core.tsx
packages/webcomponents/src/components/payment-details/test/get-payment-details.spec.ts
packages/webcomponents/src/components/payment-details/test/payment-details-core.spec.tsx
packages/webcomponents/src/components/payment-details/test/payment-details.spec.tsx
packages/webcomponents/src/components/payments-list/get-payments.ts
packages/webcomponents/src/components/payments-list/payments-list-core.tsx
packages/webcomponents/src/components/payments-list/test/get-payments.spec.ts
packages/webcomponents/src/components/payout-details/get-payout-details.ts
packages/webcomponents/src/components/payout-details/payout-details-core.tsx
packages/webcomponents/src/components/payout-details/test/get-payout-details.spec.ts
packages/webcomponents/src/components/payout-details/test/payout-details-core.spec.tsx
packages/webcomponents/src/components/payouts-list/get-payouts.ts
packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
packages/webcomponents/src/components/payouts-list/test/get-payouts.spec.ts
packages/webcomponents/src/components/payouts-list/test/payouts-list-core.spec.tsx
packages/webcomponents/src/components/payouts-list/test/payouts-list.spec.tsx

**Description**:
This pull request updates all components that utilize authToken to uniformly handle API errors related to token expiration. Specifically, when an expired token is detected, each component will now emit an error event with the error code not-authenticated. This ensures consistent error handling across our application, improving stability and the user authentication experience.
Links
-----
#424 
--------------
- On any task
To force the error state you can use this expired token: `eyJraWQiOiJqdXN0aWZpLTQxNTczZmIyNjU0MDVmNDY0Y2UyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2F1dGguanVzdGlmaS1zdGFnaW5nLmNvbS8iLCJhenAiOiJ3Y3RfNVNKckZPWTI0YXJ5bUJRc2xTY3hvRiIsInN1YiI6IndjdF81U0pyRk9ZM …

Handle Expired authToken Across All Components

---

.changeset/mean-falcons-shop.md
apps/docs/stories/components/payment-form.stories.tsx
packages/webcomponents/src/components/payment-form/payment-form.tsx

We have a method for `enableSubmitButton` - this method is used to re-enable the PaymentForm submit button in a implementers submit flow. Because the PaymentForm only handles tokenization of payment methods, the implementer then needs to use the token to make a payment and tell the form to re-enable the submit button when that is done.
We are now adding a `disableSubmitButton` to give implementers more control, such as disabling payments prior to a prerequisite to payment 
Links
-----
--------------
- On any task
- On bugs
- Pull the branch/install/build/run dev server
- In storybook, go to the PaymentForm example
- In the developer tools / console, run `const el = …

PaymentForm disableSubmitButton method

---

.changeset/silly-phones-scream.md
apps/docs/stories/components/business-form.stories.tsx
apps/docs/stories/components/payment-provisioning.stories.tsx
packages/webcomponents/src/components/business-forms/business-form/business-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.tsx

Straight-forward PR:
- Adds optional prop: `title` to `BusinessForm` and `PaymentProvisioning` components
- allows users to update title shown on form
- updates documentation, adds controls to storybook docs
- Adds optional prop: `removeTitle` to `BusinessForm` and `PaymentProvisioning` components
- allows users to remove title shown on form
- updates documentation, adds controls to storybook docs
Links
-----
Closes #480
--------------
- On any task
Fairly easy QA - can check in Storybook

Add title and removeTitle props to BusinessForm and PaymentProvisioning

---

.changeset/fifty-cheetahs-roll.md
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx

Links
-----
Closes #489 
--------------
- On any task

Add call to validate form before submitting by hitting Add button

---

.changeset/olive-beers-push.md
packages/webcomponents/src/components/business-forms/business-form/business-representative/business-representative.tsx
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx
packages/webcomponents/src/components/business-forms/schemas/business-address-schema.ts
packages/webcomponents/src/components/business-forms/schemas/business-core-info-schema.ts
packages/webcomponents/src/components/business-forms/schemas/business-identity-schema.ts
packages/webcomponents/src/components/business-forms/schemas/schema-helpers.ts
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts
packages/webcomponents/src/components/business-forms/utils/payload-parsers.ts
packages/webcomponents/src/utils/form-input-masks.ts

~NOTE: This PR is in line after #488 - that one needs to be reviewed and merged first.~
This one is ready to go! 
This PR builds on the previous one and completes validations for the identity forms. 
This PR does the following:
- Moves schema validations used in schema files to `schema-validations.ts`
- Adds validation logic to identity schemas. 
- changes SSN field in identity form to `form-control-number-masked`, in conjunction with its own validation logic. 
Links
-----
Closes #458
--------------
- On any task
BusinessForm:
PaymentProvisioning:

Improve validations and logic for identity forms (Representatives and Owners)

---

.changeset/wise-parrots-appear.md
packages/webcomponents/src/components/payment-method-form/payment-method-form.tsx

Links
-----
Closes #498 
--------------
- On any task

Fix ready event for card-form and bank-account-form

---

.changeset/witty-months-refuse.md
packages/webcomponents/src/api/Business.ts
packages/webcomponents/src/components/business-details/generic-info-details/generic-info-details.tsx
packages/webcomponents/src/components/business-details/generic-info-details/test/__snapshots__/generic-info-details.spec.tsx.snap
packages/webcomponents/src/components/business-forms/business-form/business-core-info/business-core-info.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step.tsx
packages/webcomponents/src/components/business-forms/schemas/business-core-info-schema.ts
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts
packages/webcomponents/src/components/business-forms/utils/business-form-types.ts

reverts change that removed `business_structure` from forms. Requested by back-end to revert this change 
Links
-----
Closes #508 
--------------
- On any task

Add business_structure back to business forms

---

.changeset/smart-lies-reflect.md
packages/webcomponents/src/components/business-forms/schemas/schema-helpers.ts
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts

Request from customer success team - ensure that clients cannot enter `PO Box` or `P.O. Box` in address lines 1 or 2 for business or identity addresses. 
NOTE: This should be merged after PR #501 
Links
-----
Closes #492
--------------
- On any task

Check for PO Box in Address Validations

---

apps/docs/stories/components/checkout.stories.tsx
apps/docs/stories/theme.tsx
apps/docs/stories/themes/dark.ts
apps/docs/stories/themes/index.ts
apps/docs/stories/themes/light.ts

Adds a theme switching capability to the Checkout component story. We will want to roll this out to all components later, which will require additional styles to be added to the themes.
Links
-----
--------------
- On any task
- On bugs
- Run the branch locally
- Go to the Checkout component story

Checkout theme switcher

---

packages/webcomponents/src/api/Api.ts
packages/webcomponents/src/api/services/business.service.ts
packages/webcomponents/src/api/services/checkout.service.ts
packages/webcomponents/src/api/services/payment.service.ts
packages/webcomponents/src/api/services/payout.service.ts
packages/webcomponents/src/api/services/reports.service.ts
packages/webcomponents/src/components/business-forms/business-form/business-form.tsx
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step.tsx
packages/webcomponents/src/components/business-list/business-list.tsx
packages/webcomponents/src/components/payment-balance-transactions/payment-balance-transactions.tsx
packages/webcomponents/src/components/proceeds-list/proceeds-list.tsx
packages/webcomponents/src/components/refund-form/refund-form.tsx
packages/webcomponents/src/components/subaccount-details/subaccount-details.tsx
packages/webcomponents/src/components/subaccounts-list/subaccounts-list.tsx

This PR updates the Api class to accept a single object parameter instead of two separate arguments. The new usage is `Api({ authToken, iframeOrigin })` instead of `Api(authToken, iframeOrigin)`.
The reason being that the analytics endpoint does not receive an authToken. Consequently, the Api class has been updated to handle cases where `authToken` is absent.
This changes nothing in the components usage.
--------------
- On any task
[ ] - All components should be still loading and saving data without errors

Refact(Api): Change Api props to receive an object instead of two arguments

---

.changeset/chilled-dancers-provide.md
packages/webcomponents/src/components/payment-form/payment-form.tsx

Fix issue with PaymentForm where card form is being shown instead of bank account form when card prop is false and bank-account prop is true
Links
-----
Fixes https://github.com/justifi-tech/web-component-library/issues/527
--------------
- On any task
- On bugs
Run the branch locally, and in the PaymentForm example try the following
- set card prop to `false` and bank account to `false`, the card form should show (something needs to show, card is the fallback)
- set card prop to `true` and bank account to `true`, the payment method toggle should show and user can flip between card form and bank account form
- card form `true`, bank account `false`
- bank account `true`, card `false

Add getSelectedPaymentMethodType method to PaymentForm

---

.changeset/weak-hairs-notice.md
packages/webcomponents/src/components/payment-form/payment-form.tsx
packages/webcomponents/src/components/payment-form/test/payment-form.spec.tsx

Fixes an existing bug on the PaymentForm related to the card and bankAccount props. Removes the default `true` for card prop that never gets changed, and thus never allows the other prop to work correctly. 
Links
-----
Closes #537 
--------------
- On any task

Fix PaymentForm prop logic for card and bankAccount

---

.changeset/kind-suns-bathe.md
packages/webcomponents/src/components/business-forms/business-form/business-representative/business-representative.tsx
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx
packages/webcomponents/src/components/business-forms/schemas/business-identity-schema.ts
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts

This PR fixes a bug that could potentially occur on the Owners Form step - due to improved validation rules for the SSN field. 
Links
-----
Closes #534 
--------------
- On any task
Changes are applied to the identity schema, which means the validation logic applies to the following sub components: `owner-form.tsx`, `business-representative-form.tsx` and `business-representative-form-step.tsx`.

Make SSN Optional in form if ssn_last4 is present

---

apps/docs/stories/themes/dark.ts
apps/docs/stories/themes/light.ts
apps/docs/stories/utils/css-variables.tsx
packages/webcomponents/src/components/checkout/payment-method-options.scss
packages/webcomponents/src/styles/root.scss

This changes the radio-buttons border/background/box-shadow when selected/focused to grey color instead of blue.
- The blue color is from Bootstrap `$primary` and it's the same one on focused regular inputs. However, on radio buttons it looks odd. (Decided to keep the box-shadow blue as it is also on inputs)
**Code explanation**: 
- `$secondary` and `$dark` are Bootstrap variables that are accessible on our code the same way `$primary` is.
Links
-----
[#532](https://github.com/justifi-tech/web-component-library/issues/532)
--------------
- On any task
[ ] Go to http://localhost:6006/?path=/story/payment-facilitation-payments-checkout--basic
The radio buttons should not have the default bootstrap $primary (blue) color when …

532 checkout radio button default border color is incorrect

---

.changeset/nice-feet-train.md
packages/webcomponents/src/components/billing-form/billing-form-schema.ts
packages/webcomponents/src/components/billing-form/billing-form.tsx
packages/webcomponents/src/components/billing-form/test/billing-form.spec.tsx

Refactors the billing form to use `FormController`, and `form-control` inputs. 
Uses schema validations for address lines that we created for Business Form schemas. 
I didn't do it in this PR, but we should follow this one up, eventually, with a PR that deletes the old input components used in billing-form, and finds a new home for the schema validations in a top level directory to be shared with all components cleanly. 
Links
-----
Closes #526 
--------------
- On any task
- On bugs

Improve address validation billing form

---

packages/webcomponents/src/api/Analytics.ts
packages/webcomponents/src/api/services/analytics.service.ts
packages/webcomponents/src/components/business-details/business-details.tsx
packages/webcomponents/src/components/business-details/test/business-details.spec.tsx
packages/webcomponents/src/utils/utils.ts

This PR creates the following.
- Analytics class - A class that will track the events and lifecycle methods of a component and send data to analytics.
- Analytics service - A service to post to analytics Api.
This PR also implements the Analytics in the BusinessDetails component as first reference.
Another PR will follow up this with the implementation on the rest of the components.
Links
-----
#496 
--------------
- On any task
[ ] - BusinessDetails: When the component loads, there should be a successful network request to `analytics` with a request payload like this: 
```
{
"event_type": "init",
"data": {
"component_name": "JUSTIFI-BUSINESS-DETAILS",
"component_version": "4.13.0",
"client_user_agent": "Mozilla/5.0 …
```

feat: Analytics class and BusinessDetails implementation

---

packages/webcomponents/src/components/form/form-control-checkbox.scss
packages/webcomponents/src/components/form/form-control-checkbox.tsx
packages/webcomponents/src/components/form/test/__snapshots__/form-control-checkbox.spec.tsx.snap
packages/webcomponents/src/components/form/test/form-control-checkbox.spec.tsx

Quick PR to add a new `form-control` component that renders checkbox input.
Probably will get some updates in the next PR, but this should make it easier to review the terms and conditions PR if we get this one out of the way now. 
Links
-----
Closes #547 
--------------
- On any task
We can do a more thorough QA when we render the terms and conditions form step which will actually use this checkbox component. For right now, I believe the test coverage is sufficient.

Form control checkbox component

---

packages/webcomponents/src/api/Document.ts
packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-input-group.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/input-configurations.ts
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.tsx
packages/webcomponents/src/components/business-forms/schemas/business-document-upload-schema.ts
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts
packages/webcomponents/src/utils/utils.ts

This PR builds the changes introduced in #521 
Beginning with this PR - the `PaymentProvisioning` component holds `business_payment_volume` in state after completing the additional questions form step, and uses this number to determine which file inputs are rendered and required during validation. 
Links
-----
Closes #553 
--------------
- On any task
In order to test this properly, you'll need to just complete the form a few times, and each time you need to pay special attention to the value you provide during the Additional Questions form step - to `Anticipated Payment Volume` (the second field on the page)
You can use the same business for these first steps:
Case A - `payment_volume` is less than `249,999` 
You will need …

Document uploading field logic

---

package.json
pnpm-lock.yaml
turbo.json

This adds the changes needed for migrating Turbo from v1 to v2.
https://turbo.build/blog/turbo-2-0
Turbo v2 changes include improving the terminal output, which also solves the problem with the unit tests output not highlighted.
Links
-----
#579 
--------------
- On any task
[ ] - Run `pnpm install` on root folder and try to build the project. It should build without errors.
[ ] - Run `pnpm test:watch` on the root folder. It should run the tests and the output should have syntax highlight

Migrate turbo to latest

---

.changeset/chilled-dancers-pretend.md
apps/docs/stories/components/payment-provisioning.stories.tsx
packages/webcomponents/src/api/ComponentError.ts
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/bank-account/business-bank-account-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.scss
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/terms-and-conditions/business-terms-conditions-form-step.tsx
packages/webcomponents/src/components/business-forms/utils/helpers.ts

- No longer render `form-alert` in `PaymentProvisioning` on server / API errors
- Emit `error-event` typed as `ComponentError` to be in step with other component error handling
- emits on load if there is no auth token or business id, and emits on failure to fetch or send data. 
- Removes prop `hideErrors` from `PaymentProvisioning` since there are no longer any alerts to show or hide in this component. 
Links
-----
Closes #454 
--------------
- On any task
- On bugs

Payment provisioning component error event

---

.changeset/beige-lions-draw.md
packages/webcomponents/src/api/Analytics.ts
packages/webcomponents/src/components/checkout/checkout.tsx

After some debugging it seems that the error os only caused because at some point the Analytics is called before the component is instantiated. I attempted to call Analytics in other life cycles but the error continued happening. 
Adding the validation to only call `addEventListener` when it's actually a function fixed the error without breaking the Analytics functioning
**Note: This bug was only reproducible on a demo-app**
* This adds an error bound to prevent addEventListener to be called on undefined
Links
-----
#594 
--------------
- On any task
[ ] - Run a demo app (any) and add a symlink to the web-components. Any error regarding `addEventListener` is not a function should be visible on the console. Also a network …

Add an error bound

---

apps/docs/.storybook/main.ts
apps/docs/.storybook/manager.ts
apps/docs/stories/components/bank-account-form-docs.stories.mdx
apps/docs/stories/components/bank-account-form.stories.tsx
apps/docs/stories/components/business-details.stories.tsx
apps/docs/stories/components/business-form.stories.tsx
apps/docs/stories/components/card-form-docs.stories.mdx
apps/docs/stories/components/card-form.stories.tsx
apps/docs/stories/components/checkout-docs.stories.mdx
apps/docs/stories/components/checkout.stories.tsx
apps/docs/stories/components/gross-payment-chart.stories.tsx
apps/docs/stories/components/payment-details.stories.tsx
apps/docs/stories/components/payment-form-docs.stories.mdx
apps/docs/stories/components/payment-form.stories.tsx
apps/docs/stories/components/payment-provisioning.stories.tsx
apps/docs/stories/components/payments-list-docs.stories.mdx
apps/docs/stories/components/payments-list.stories.tsx
apps/docs/stories/components/payout-details.stories.tsx
apps/docs/stories/components/payouts-list-docs.stories.mdx
apps/docs/stories/components/payouts-list.stories.tsx
apps/docs/stories/utils/base-args.ts
apps/docs/stories/utils/css-variables.tsx
apps/docs/stories/utils/decorators.ts
packages/webcomponents/src/components/business-list/business-list.stories.ts
packages/webcomponents/src/components/payment-balance-transactions/payment-balance-transactions.stories.ts
packages/webcomponents/src/components/proceeds-list/proceeds-list.stories.ts
packages/webcomponents/src/components/refund-form/refund-form.stories.ts
packages/webcomponents/src/components/subaccount-details/subaccount-details.stories.ts
packages/webcomponents/src/components/subaccounts-list/subaccounts-list.stories.ts

This adds the `theme` prop to base-args in order to be possible to switch between "basic" and "custom" styles on the story controls.
As a consequence of this change, the "custom" extra stories for each component were removed. Now we have only the "basic" story with a "theme" prop under "theming" section on the story controls.
* In the prop description, added a link to the [Introduction](https://storybook.justifi.ai/?path=/docs/introduction--docs#styling-components-with-variables) to show an example of the CSS variables available.
(top toolbar buttons) 
* ~~The top toolbar buttons are default and it seems that they cannot be removed.~~ Yes they got removed 👍 
Links
-----
#525 
--------------
- On any task
[ ] …

Add 'custom-styled' prop to baseArgs

---

apps/docs/stories/components/BankAccountForm/Docs.mdx
apps/docs/stories/components/CardForm/Docs.mdx
apps/docs/stories/frameworks/react.mdx
apps/docs/stories/intro.mdx

* This fixes some component links across documentation
* This fix "note" style on intro-docs
**Before:** 
**After**
Links
-----
--------------
- On any task
[ ] - All internal links to components on the docs should be working fine.
[ ] - The "Note" right after the "See full list of CSS variables available" should look like a note block not overloading the screen container

Fix component links on documentation

---

.changeset/small-paws-hammer.md
packages/webcomponents/src/api/services/business.service.ts
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-actions.ts
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-steps.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/readme.md
packages/webcomponents/src/components/form/readme.md

- Refactors `BusinessCoreInfoFormStep` into base component and core component structure
- Add `patchBusiness` functionality to `business.service.ts`
- Use Stencil `Listen` method to listen for `form-loading` event instead handling it in the component attributes
- this will be done for each of the form-step components as we refactor them in these PRs.
Links
-----
Closes #605 
--------------
- On any task
Ideally everything should function as it did before. This PR only changes the first form step, the core info data, so you only need to test the first step for this PR.

Refactor CoreInfo form step to use core component structure

---

apps/docs/stories/themes/dark.ts
apps/docs/stories/themes/light.ts
apps/docs/stories/utils/css-variables.tsx

This PR adds some the missing CSS variables for styling the radio buttons on the light and dark theme.
--------------
- On any task
[ ] - Radio button on light theme should look like:
[ ] - And on dark theme should look like:

Add missing CSS variables

---

.changeset/chatty-trainers-repeat.md
apps/docs/stories/components/Checkout/index.stories.tsx
packages/webcomponents/src/components/billing-form/billing-form.tsx
packages/webcomponents/src/components/checkout/checkout-core.tsx
packages/webcomponents/src/components/checkout/checkout.tsx
packages/webcomponents/src/components/checkout/new-payment-method.tsx
packages/webcomponents/src/components/checkout/payment-method-options.tsx

Just like we've done for `PaymentForm`, we need to expose a method that can be used to pre-fill the billing form: https://github.com/justifi-tech/web-component-library/blob/main/packages/webcomponents/src/components/payment-form/payment-form.tsx#L57
Customers use this when they already have the end-user's billing information on file or when it was collected in a previous step before checking out
Links
-----
--------------
- On any task
- On bugs
- Check out the `fill-billing-form-test` branch of https://github.com/justifi-tech/checkout-demo
- Run the checkout demo using `npm run start` and open the browser to `localhost:3000`

Checkout: Method to fill billing information

---

.changeset/tricky-drinks-leave.md
apps/docs/stories/components/Checkout/index.stories.tsx
packages/webcomponents/src/components/checkout/checkout-core.tsx
packages/webcomponents/src/components/checkout/payment-method-options.tsx
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap

Links
-----
Closes #627 
--------------
- On any task

Move insurance slot and disable BNPL if insurance accepted

---

.changeset/stupid-parents-shave.md
packages/webcomponents/src/components/checkout/checkout-core.tsx
packages/webcomponents/src/components/checkout/new-payment-method.tsx
packages/webcomponents/src/components/checkout/payment-method-options.tsx
packages/webcomponents/src/components/checkout/payment-method-payload.ts
packages/webcomponents/src/components/checkout/readme.md
packages/webcomponents/src/components/checkout/saved-payment-method.tsx
packages/webcomponents/src/components/checkout/sezzle-payment-method.tsx

This PR commits the following change:
- Passes `insuranceValidation` into the `resolvePaymentMethod` method so that each of the payment-method components check for an insurance selection. 
- In the case of `new-payment-method.tsx` - the insurance validation is checked along with the payment and billing form validations
- In the case of `sezzle-payment-method.tsx` - it simply checks for an insurance selection before opening the sezzle window
- in the case of `saved-payment-method.tsx` - it simply checks for an insurance selection before posting the checkout completion.
Links
-----
Closes #634 
--------------
- On any task
It would be best to test the checkout component with AND without insurance included just to be safe.

Ensure insuranceValidation is called before resolvePaymentMethod

---

mockData/mockGetCheckoutSuccess.json
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap
packages/webcomponents/src/components/payment-method-form/payment-method-responses.ts

This PR just adds the `invalid_reason` to the respective response types and updates the checkout mock to sync with most recent changes
Links
-----
#600 
--------------
- On any task
- On bugs
No need to QA this

600 cardcreateresponse add invalid reason

---

.changeset/angry-bobcats-yawn.md
packages/webcomponents/src/components/checkout/_jfi-checkbox.scss
packages/webcomponents/src/components/checkout/checkout-core.tsx
packages/webcomponents/src/components/checkout/checkout.tsx
packages/webcomponents/src/components/checkout/new-payment-method.tsx
packages/webcomponents/src/components/checkout/payment-method-options.scss
packages/webcomponents/src/components/checkout/payment-method-options.tsx
packages/webcomponents/src/components/checkout/readme.md
packages/webcomponents/src/components/checkout/save-new-payment-method.tsx
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap

NOTE: this PR will need to be coordinated with the following PR for payments-js:
[Payments-js 136](https://github.com/justifi-tech/payments-js/pull/136
)
- Adds a checkbox below the new payment method billing form that will only render IF the checkout has an associated `payment_method_group_id`
- When checked / true, the checkout will submit the payment_method_group_id along with payment's metadata
Links
-----
Closes #629 
--------------
- On any task
- Make sure that payment_method_group_id is being sent
- Rendering a new checkout shows the saved payment method

Checkout save new payment methods

---

.changeset/tricky-rocks-relate.md
packages/webcomponents/src/components/business-forms/owner-form/owner-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx
packages/webcomponents/src/components/business-forms/schemas/business-core-info-schema.ts
packages/webcomponents/src/components/business-forms/schemas/schema-helpers.ts
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts
packages/webcomponents/src/components/form/form-control-text.tsx
packages/webcomponents/src/components/form/utils.tsx

This PR makes the following changes:
- Tax ID Field (Core Info / First form step)
- label changed from `Tax ID` => `Tax ID (EIN or SSN)`
- removed mask that was created for Tax ID specificly
- adds keyDownHandler to prevent alphabet / special character input. Input allows numbers only. 
- Validation is largely the same, but it no longer checks for the taxIDRegex. 
- SSN Field (Representative and Owner Form Steps)
- removed logic that changed label for SSN field if ssn_last4 returns a value. Label always shows `SSN`
- original validation is still in place, so the previous logic still holds true. If ssn_last4 is returned in fetch request, then this field will not be required for this business. 
These are really the only changes worth mentioning - but I did update the files I was working on …

Adjustments to SSN and Tax ID fields in PaymentProvisioning component

---

.changeset/purple-dogs-compare.md
packages/webcomponents/src/components/checkout/payment-method-option-utils.tsx
packages/webcomponents/src/components/checkout/payment-method-options.tsx
packages/webcomponents/src/utils/utils.ts

* This PR makes BNPL the default option after saved payment methods by pushing it before any other payment method in the array. (Jake's PR)
* This also add a new `type` property to the payment method options and filters out the saved payment methods accordingly with `disabled-bank-account` and `disabled-credit-card` props.
Links
-----
#625 
--------------
- On any task
- On bugs
This can be tested either in the demo-app or in Storybook, just need a checkout with saved credit cards or bank account payment methods
[ ] - passing `disable-credit-card=true` should hide saved credit card payment methods
[ ] - passing `disable-bank-account=true` should hide saved bank account payment methods

Hide saved disabled payment methods

---

packages/webcomponents/src/components/business-forms/owner-form/identity-address/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/README.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-inputs.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-steps.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/readme.md
packages/webcomponents/src/components/form/readme.md

- Refactor Representative form step of PaymentProvisioning component to use core component structure
- Abstract form inputs to their own component file for additional tidiness and organization
Links
-----
Closes #616 
--------------
- On any task
Ideally everything should function as it did before. This PR only changes the fourth form step, the Representative form, so you only need to test the fourth step for this PR.

PaymentProvisioning - Refactor representative form step

---

apps/docs/stories/components/Checkout/index.stories.tsx
mockData/mockGetCheckoutSuccess.json
mockData/mockPostCheckoutSuccess.json
packages/webcomponents/src/api/Checkout.ts
packages/webcomponents/src/api/ComponentError.ts
packages/webcomponents/src/components/checkout/checkout-actions.ts
packages/webcomponents/src/components/checkout/checkout-core.tsx
packages/webcomponents/src/components/checkout/checkout.tsx

**DESCRIPTION**
* This PR adds some logic to emit an error event when checkout status is expired or completed
Links
-----
#639 
-------------
While we don't have yet `completed` and `expired` statuses on our API yet, it's still possible to test this by overriding the request response on the browser:
* On the network tab, right click the checkout request, and click "Override content"
* Edit the response JSON changing the status to `completed` or `expired` and save.
* An error event should be emitted with error details for each case.

handle expired and completed checkout statuses

---

.changeset/famous-steaks-tickle.md
packages/webcomponents/src/components/business-forms/utils/payload-parsers.ts

This PR fixes a reported bug with the BusinessForm and PaymentProvisioning Form components - the `associated_accounts` property will now be parsed out from payloads sent from this component. 
Links
-----
Closes #659 
--------------
- On any task

Parse associated_accounts from business payload

---

.changeset/many-hairs-grab.md
packages/webcomponents/src/components/insurance/season-interruption/season-interruption-insurance.tsx

This PR adds Analytics service on the Season Interruption Component
*. All other components are actually connected with Analytics and sending along the component name as expected.
Links
-----
#657 
--------------
- On any task
- On bugs

add analytics to insurance component

---

.changeset/fluffy-spies-enjoy.md
packages/webcomponents/src/components/payment-method-form/payment-method-form.tsx
packages/webcomponents/src/components/payment-method-form/test/payment-method-form.spec.tsx

* In Safari, the `card-form` and `bank-account-form` components were attaching the `eventListener` too late to capture the `StyleOverrides` event. To fix this, the `sendStyleOverrides` call in the `payment-method-form` web component has been moved from the iframe's `onLoad` event to the `ready` event, which occurs later.
Links
-----
#678 
--------------
- On any task
- On bugs
[ ] - The card-form/bank-account-form should have the same styles as the billing-form and other inputs in the checkout on all browsers (in special Safari)

fix style bug on Safari

---

.changeset/four-suns-search.md
apps/docs/stories/utils/mockAllServices.ts
packages/webcomponents/src/api/Payment.ts
packages/webcomponents/src/api/services/payment.service.ts
packages/webcomponents/src/components/payments-list/get-payments.ts
packages/webcomponents/src/components/payments-list/payments-list-filters.tsx
packages/webcomponents/src/components/payments-list/payments-list.tsx
packages/webcomponents/src/components/payments-list/test/get-payments.spec.ts
packages/webcomponents/src/components/payments-list/test/payments-list-core.spec.tsx

- Add `payment_id` text search filter for payments-list-filters
- Add passthrough logic for package version check request to NPM when using mock data
- Add optional apiOrigin prop for payments-list component and associated requests
Links
-----
Closes #727 
Closes #728 
--------------
- On any task
- On bugs

Add New Payment ID Filter / optional api Origin prop for payments-list

---

apps/docs/stories/themes/dark.ts
apps/docs/stories/themes/light.ts
apps/docs/stories/utils/css-variables.tsx
packages/webcomponents/src/components/checkout/payment-method-options.css
packages/webcomponents/src/components/checkout/readme.md
packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap
packages/webcomponents/src/components/payouts-list/test/__snapshots__/payouts-list-core.spec.tsx.snap
packages/webcomponents/src/styles/root.css

This PR commits the following changes: 
- Remove all CSS variables that are not used by the iframe-components.
Links
-----
--------------
- On any task
- On bugs

Remove CSS variables

---

.changeset/eight-bottles-punch.md
packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step-core.tsx

This PR commits a relatively straightforward change:
- Conditionally render `business_recurring_payments_percentage` input field based on value of `business_recurring_payments` input. 
Links
-----
Closes #734 

Add conditional render logic to recurring payments followup question

---

.changeset/slimy-monkeys-sneeze.md
apps/docs/stories/components/PaymentProvisioning/example.ts
apps/docs/stories/components/PaymentProvisioning/index.stories.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/bank-account/business-bank-account-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/README.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/input-configurations.ts
packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/terms-and-conditions/business-terms-conditions-form-step.tsx
packages/webcomponents/src/components/business-forms/utils/business-form-types.ts

In our 5.x.x release, we plan to adjust the expected behavior and payload of our `submitted` event in the `payment-provisioning` component. We plan to update the behavior of `submitted` so that it is only emitted at the very end of the component form UI flow. This will bring its behavior in line with our other components that also emit a `submitted` event. 
This change will be considered a breaking change, which is why we are waiting until our 5.x.x release to commit this change. In the mean time, this PR begins preparing for this change by adding a new event to the `payment-provisioning` component: `form-step-completed`
This new event will be emitted alongside `submitted` for now, until we alter the `submitted` event's behavior to only emit at the very end of the form flow. 
The story …

Add form step completed event

---

.changeset/perfect-mice-clap.md
packages/webcomponents/src/api/Payment.ts
packages/webcomponents/src/components/business-forms/owner-form/owner-form-inputs.tsx
packages/webcomponents/src/components/form/form-control-date.tsx
packages/webcomponents/src/components/form/test/__snapshots__/form-control-date.spec.tsx.snap
packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap
packages/webcomponents/src/components/payments-list/payments-list-core.tsx
packages/webcomponents/src/components/payments-list/payments-list-filters.tsx
packages/webcomponents/src/components/payments-list/test/__snapshots__/payments-list-core.spec.tsx.snap
packages/webcomponents/src/utils/utils.ts

This PR commits a handful of smaller changes to `payments-list`
- Removed `Payment ID` column
- Updated column name `Card Holder` to now say `Account Holder`
- Now showing currency type in `Amount` column
- Added `Type` column to show Card and ACH payments
- Changed wording of `Successful` payment status badge to `Succeeded`
- Updated some status badge colors to reflect Figma mockup
- Added `Canceled` payment status badge for canceled payments
- Updated start and end date filter inputs to allow user to choose times, allowing for even more granular payment filtering
- (I believe I fixed an issue with the date input that we hadn't discussed - it now converts the date string to UTC timezone when applying the filters for the payments list, and converts it back to local time for proper display …

Payments List Refactors

---

packages/webcomponents/src/components/billing-form/readme.md
packages/webcomponents/src/components/form/form-control-date.tsx
packages/webcomponents/src/components/form/readme.md
packages/webcomponents/src/components/form/test/__snapshots__/form-control-date.spec.tsx.snap
packages/webcomponents/src/components/form/test/form-control-date.spec.tsx

Add logic to pass a maxDate prop to form-control-date component, uses current date as default value, but can pass maxDate as a prop if needed for some reason in the future. 
This is mainly to fix failing snapshot tests for the form-control-date component since adding the max date attribute
Links
-----
--------------
- On any task
- On bugs

Add maxDate as prop to form-control-date

---

.changeset/popular-spoons-push.md
packages/webcomponents/src/components/business-forms/owner-form/owner-form-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/business-additional-questions-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/additional-questions/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/bank-account/business-bank-account-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/business-owners-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/business-owners/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/README.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-representative/business-representative-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/document-uploads/business-document-upload-form-step.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/legal-address-form-step-core.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/legal-address-form/readme.md
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-form-steps.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/terms-and-conditions/business-terms-conditions-form-step.tsx
packages/webcomponents/src/components/business-forms/utils/business-form-types.ts

This PR modifies the `submitted` event behavior of the payment-provisioning component to only emit at the very end of the form after the provisioning request has been completed. 
Links
-----
Closes #716 
--------------
- On any task

Remove submitted from individual form steps in payment provisioning component

---

.changeset/silly-pillows-check.md
packages/webcomponents/src/components/checkouts-list/checkouts-list-core.tsx
packages/webcomponents/src/components/checkouts-list/checkouts-list.tsx
packages/webcomponents/src/components/checkouts-list/test/checkouts-list-core.spec.tsx
packages/webcomponents/src/components/terminals-list/terminals-list-core.tsx
packages/webcomponents/src/components/terminals-list/terminals-list.tsx
packages/webcomponents/src/components/terminals-list/test/terminals-list-core.spec.tsx
packages/webcomponents/src/utils/table.ts

Links
-----
--------------
- On any task
- On bugs

Refactor render timing for terminals and checkouts list components

---

.changeset/wild-weeks-turn.md
packages/webcomponents/src/components/business-forms/schemas/business-core-info-schema.ts
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts

Several fields in the Payment Provisioning component have had their validation rules relaxed to allow for special characters to be entered. 
Links
-----
Closes #780 
--------------
- On any task
Several fields in the Payment Provisioning component have had their validation rules relaxed to allow for special characters to be entered. 
Ensure that the following fields have looser validation requirements: 
`Step 1 - Core Info`
`Step 2 - Address`
`Step 4 - Representative`
`Step 5 - Owner`
`Step 6 - Bank`

Loosen string validation requirements for several fields in Payment Provisioning component

---

.changeset/ten-turkeys-grow.md
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts

Links
-----
Closes #785 
--------------
- On any task

Update bank account schema to allow for 7 character account numbers

---

.github/workflows/chromatic-deployment.yaml
.github/workflows/publish.yml
.github/workflows/storybook.yml
.github/workflows/test.yaml

This PR makes changes in the Github Actions workflows to add the cache option on the install tasks.
Reference: 
https://github.com/actions/setup-node#caching-global-packages-data
https://github.com/actions/cache
https://github.com/actions/setup-node?tab=readme-ov-file#caching-global-packages-data
https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
Links
-----
#805 
--------------
- On any task
- On bugs
[ ] - I don't think we need to directly QA this right now. But we should pay attention in next PRs and releases to the time the actions are going to take to complete.

Optimize Github Actions to leverage caching and action dependencies 

---

apps/docs/stories/utils/mockAllServices.ts
mockData/mockBusinessProvisioningSuccess.json

This PR adjusts the mock data passthrough for patching business's to return a response object that is structured the same as a real world example. 
Also updated the mock response for the Provisioning request to include an accurate `payload` property. 
Note - this is purely for testing the component in Storybook with mock data enabled. 
Links
-----
Closes #810 

Return more accurate response data for payment provisioning mock data

---

apps/component-examples/css/theme.css
apps/component-examples/examples/payment-provisioning.js
apps/component-examples/utils/random-business-names.js

- Adds code to `payment-provisioning.js` allowing file to fetch access token, create a business using a randomly generated name, post web component token for this business, and render the component to the page. 
Links
-----
Closes #826 

Add Payment provisioning example file

---

.changeset/kind-parrots-roll.md
packages/webcomponents/src/components/checkout/checkout-core.tsx
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout-core.spec.tsx.snap
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap
packages/webcomponents/src/styles/parts.ts

Based on a customer request, this PR adds the `checkout-summary` part, so it can be hidden.
Links
-----
#840 
--------------
To test this, add to `apps/component-examples/css/example.css` the following: 
```
::part(checkout-summary) { display: none; }
```

Add checkoutSummary part to checkout component and update snapshots

---

.changeset/kind-hornets-divide.md
apps/docs/stories/components/TokenizePaymentMethod/index.stories.tsx
packages/webcomponents/src/components/checkout/new-payment-method.tsx
packages/webcomponents/src/components/checkout/payment-method-payload.ts

Adds `data` alongside with the `token` on the `sumit-event`
```
export interface PaymentMethodPayload {
data?: CreatePaymentMethodResponse;
token?: string;
bnpl?: {
order_uuid: string;
status: string;
session_uuid: string;
};
error?: {
code: string;
message: string;
decline_code: string;
};
validationError?: boolean;
}
```
Links
-----
#854 
--------------
- On any task
- On bugs

increment submit-event payload to include full payment-methods response and update documentation

---

.changeset/silver-masks-confess.md
packages/webcomponents/src/components/business-forms/schemas/schema-validations.ts

Links
-----
Closes #872 
--------------
- On any task
**General:**
Payment-provisioning component:

Update bank account form schema to allow shorter bank account numbers to be entered

---

.changeset/cool-oranges-repair.md
apps/component-examples/examples/tokenize-payment-method.js
apps/docs/stories/components/TokenizePaymentMethod/index.stories.tsx
packages/webcomponents/src/components/tokenize-payment-method/tokenize-payment-method.tsx

- tokenize method in `tokenize-payment-method` component now returns the response from the tokenize request, the same as the submit-event in this component. 
Links
-----
Closes #875 
--------------
- On any task
Example file is already set up in this branch to make testing this easy. 
In `tokenize-payment-method.js`:
Update line 66:
`  const hideSubmitButton = false; =>   const hideSubmitButton = true;`
**General:**
tokenize component:

Return PaymentMethodPayload in tokenize method in tokenize component

---

packages/webcomponents/setupTests.js
packages/webcomponents/src/components/checkout/bank-account-form/bank-account-form.tsx
packages/webcomponents/src/components/checkout/card-form/card-form.tsx
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap

Change our .env files to not use the version number on the route path.
- `IFRAME_ORIGIN=http://localhost:3003/v2` - 👎
- `IFRAME_ORIGIN=http://localhost:3003` - 👍
**REMINDER** : The `IFRAME_ORIGIN` Github Environment secret must be updated before this gets published
https://github.com/justifi-tech/web-component-library/settings/secrets/actions
Links
-----
#877 
--------------
- On any task
- On bugs
In order to test this, remove the `/v2` from `IFRAME_ORIGIN` env variable on `packages/webcomponents/.env`.
[ ] - `pnpm dev:checkout`, `pnpm dev:checkout-with-insurance` and `pnpm dev:tokenize-payment-method` should display correctly the card and bank account form payment methods. (If the iframe origin is wrong, …

Update iframe origin env variable URLs to ignore the version segment

---

.changeset/clever-cars-search.md
apps/component-examples/examples/checkouts-list-with-filters.js
apps/component-examples/examples/checkouts-list.js
apps/component-examples/examples/payments-list-with-filters.js
apps/component-examples/examples/payments-list.js
packages/webcomponents/src/api/Checkout.ts
packages/webcomponents/src/components/checkouts-list/checkouts-list-core.tsx
packages/webcomponents/src/components/checkouts-list/checkouts-list-filters.tsx
packages/webcomponents/src/components/checkouts-list/checkouts-list-params-state.ts
packages/webcomponents/src/components/checkouts-list/test/checkouts-list-with-filters.spec.tsx
packages/webcomponents/src/components/payments-list/payments-list-core.tsx
packages/webcomponents/src/components/payments-list/payments-list-filters.tsx
packages/webcomponents/src/styles/parts.ts

- Allows query params for checkout status and payment mode to be passed as props to `checkouts-list-filters` component
- Adds new parts to adjust or hide checkouts filters menu, or specific inputs.
- Updates example files `payments-list`, `payments-list-with-filters`, `checkouts-list`, and `checkouts-list-with-filters` with organized env variables. Update sizing and display for payments-list and checkouts-list example files.
Links
-----
Closes #861 
--------------
- On any task
**General:**
**Checkouts-List:**
For these you should run `pnpm dev:checkouts-list-with-filters` example file.

Checkouts list filters query param props

---

apps/component-examples/examples/order-terminals.js
apps/component-examples/package.json
apps/docs/stories/components/OrderTerminals/Docs.mdx
apps/docs/stories/components/OrderTerminals/example.ts
apps/docs/stories/components/OrderTerminals/index.stories.tsx
package.json
packages/webcomponents/src/components/order-terminals/order-terminals.tsx
packages/webcomponents/src/components/order-terminals/test/order-terminals.spec.tsx

This PR commits the following: 
- Creates the basic boilerplate code for the `justifi-order-terminals` component.
- Creates an initial Docs file and Storybook story with some information about the component (can be improved later).
- Create some basic unit tests (smoke tests so far).
- Create an example file that can be run by the command: `pnpm dev:order-terminals`.
**NOTE** - I haven't implemented yet the `core component` pattern that we have, because I wanna test an alternative for mocking services in the test files. So this part I'll add later when the component actually have more api interaction.
Links
-----
#865 
--------------
- On any task
- On bugs
Running Storybook: `pnpm dev`;
Running `pnpm …

Add Order Terminals component and example setup

---

apps/component-examples/examples/checkout-with-insurance.js
apps/docs/stories/utils/mockAllServices.ts
packages/webcomponents/src/api/Analytics.ts

The main focus of this PR is to add some logic to bypass the Analytics service call when origin is localhost and storybook.
This will help to maintain Datadog data clean.
Also this PR commits some improvements in the checkout example variables organization.
Links
-----
#886 
--------------
- On any task
- On bugs

Refactor Analytics logic to bypass calls from localhost and storybook

---

apps/component-examples/css/example.css
apps/component-examples/examples/checkouts-list-with-filters.js
apps/component-examples/examples/checkouts-list.js
apps/component-examples/examples/payments-list-with-filters.js
apps/component-examples/examples/payments-list.js
apps/component-examples/examples/payouts-list-with-filters.js
apps/component-examples/examples/payouts-list.js
apps/component-examples/examples/terminal-orders-list.js
apps/component-examples/examples/terminals-list-with-filters.js
apps/component-examples/examples/terminals-list.js
apps/component-examples/package.json
package.json
packages/webcomponents/src/components/pagination-menu/readme.md
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list-core.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-table.tsx

- Creates `justifi-terminal-orders-list` component, `terminal-orders-list-core` component, `terminal-orders-table` logic, and `terminal-orders-list` js example file. 
- there is no data being fetched yet as the API is not ready, so API service files will come later
- columns are placeholder values for now until we decide how the data should be rendered and organized
- classes and types are `any` for now until we have a firm idea of what the shape of the data is
- tests will come in a later PR
Links
-----
Closes #887 
--------------
- On any task
To run the new component's example file: `pnpm dev:terminal-orders-list`

Create terminal orders list component

---

.changeset/stupid-boats-peel.md
packages/webcomponents/src/components/terminals-list/terminals-table.tsx
packages/webcomponents/src/components/terminals-list/test/__snapshots__/terminals-list-core.spec.tsx.snap

Links
-----
Closes #904 
--------------
- On any task

terminals-list: Rename provider id column to Serial Number

---

apps/component-examples/examples/checkout-with-insurance.js
apps/component-examples/examples/checkout.js
apps/component-examples/examples/tokenize-payment-method.js
packages/webcomponents/src/components/checkout/bank-account-form/bank-account-form.tsx
packages/webcomponents/src/components/checkout/card-form/card-form.tsx

Removing this once again as it does not seem especially helpful now that we have proper loading states for the card and bank account forms. We can add it back later if there is a good reason for it, but once it's introduced in a published package deprecating would be a breaking change.
Links
-----
--------------
- On any task
- On bugs

Remove 'ready' event

---

.changeset/ten-geckos-jump.md
packages/webcomponents/src/api/Payout.ts
packages/webcomponents/src/components/payouts-list/payouts-list-core.tsx
packages/webcomponents/src/components/payouts-list/payouts-table.tsx
packages/webcomponents/src/ui-components/table/event-types.ts

- Prevents table row click event from being emitted when user clicks on the CSV Download link
- Fixes cases where CSV download link was incorrectly formed, leading to failed download requests.
Links
-----
Closes #903 
Closes #899 
--------------
- On any task
General:
`payouts-list`:

Improve CSV Download on Payouts List

---

.changeset/rotten-kangaroos-perform.md
packages/webcomponents/src/api/Checkout.ts
packages/webcomponents/src/components/checkouts-list/checkouts-list-filters.tsx

This PR commits the following change:
- Fixes bug in `checkouts-list-filters` where `payment_mode` filter input sends wrong value. 
- Incorrectly sending `E-Commerce` and `Buy Now Pay Later`
- Fixed to send `ecom` and `bnpl`
Links
-----
Closes #920 
--------------
- On any task
To test this - run `pnpm dev:checkouts-list-with-filters`

Fix broken checkouts payment mode filter

---

.changeset/forty-shirts-exist.md
apps/docs/stories/components/TerminalsList/index.stories.tsx
mockData/mockTerminalsListSuccess.json
packages/webcomponents/src/api/Terminal.ts
packages/webcomponents/src/components/terminals-list/terminals-table.tsx
packages/webcomponents/src/components/terminals-list/test/__snapshots__/terminals-list-core.spec.tsx.snap

- Renames `provider_id` column back to `Provider ID`
- adds new column `provider_serial_number` / `Serial Number` used to display new property from terminals response: `provider_serial_number`
- Replaces `provider_id` with `provider_serial_number` in default column configuration for terminals-list
- `provider_id` is still available to be used as an optional column for now.
Links
-----
Closes #915 
--------------
- On any task

Show `provider_serial_number` property in `terminals-list`

---

packages/webcomponents/src/components/terminal-quantity-selector/terminal-quantity-selector.tsx

Links
-----
#917 
--------------
- On any task
- On bugs
[ ] - Now instead of displaying the description right away, it has a tooltip that contains the terminal model description

Refactor terminal quantity selector layout and improve accessibility

---

.changeset/seven-eels-peel.md
packages/webcomponents/src/api/DisputeEvidenceDocument.ts
packages/webcomponents/src/components/dispute-management/dispute-notification.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/additional-statement.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/cancellation-policy.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/customer-details.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/dispute-response-core.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/duplicate-charge.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/electronic-evidence.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/file-input-handler.ts
packages/webcomponents/src/components/dispute-management/dispute-response/product-or-service.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/refund-policy.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/shipping-details.tsx
packages/webcomponents/src/ui-components/form/form-control-file-v2.tsx
packages/webcomponents/src/ui-components/form/form-helpers/form-control-tooltip/readme.md

- Surface file upload pre-signing issues (such as file types that are not accepted) in the UI
- Change "Service Date" to a date selector
- Fix evidence type name: "cancellation_policy_file" -> "cancellation_policy"
- Fix typos in completion notification messages
- Abstract file handlers for consistent behavior
- Clear out / "replace" file uploads when a new file is selected
--------------
- On any task
- On bugs
- Pull this branch
- Edit your `.env` file (in the root of the project) to include a fresh dispute ID
- Run it using `npm install` then `pnpm dev:dispute`
- Go through the steps filling out the fields. For files, try making each one fail by selecting an unsupported file type such as `.gif`
- An …

Dispute component bug fixes

---

.changeset/dirty-maps-reflect.md
apps/component-examples/examples/payment-provisioning.js
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning-core.tsx

This PR commits the following change:
- Fixes bug in payment-provisioning component where submit button returns console error. We removed the document upload form step recently and seems we did not remove the `ref` to this step when we removed it. 
- Updates example file with organized env variables used at the top of the file
Links
-----
Closes #923
--------------
- On any task
To test this - run `pnpm dev:payment-provisioning` - the example file will generate a new business for you upon load.

Fix submission bug in payment-provisioning component

---

apps/component-examples/examples/terminal-orders-list.js
packages/webcomponents/src/actions/terminal/get-terminal-orders.ts
packages/webcomponents/src/api/TerminalOrder.ts
packages/webcomponents/src/api/services/terminal_orders.service.ts
packages/webcomponents/src/components/terminal-orders-list/terminal-order-status.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list-core.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list.tsx

- `terminal-orders-list` component requests orders data from `terminals/orders` and displays it in the table
- adds new `TerminalOrderStatus`: `created`
- Edits example file for this component to make real requests for auth token, WCT and load actual data in component.
- Component now emits `click-event` on table row click or pagination button click
- Component now emits `error-event` on fetch error, or props error (no account ID or auth token provided)
Links
-----
Closes #888
Closes #891 
--------------
- On any task

Fetch Terminal Orders Data in `terminal-orders-list` component and emit events

---

apps/component-examples/examples/terminal-orders-list-with-filters.js
apps/component-examples/package.json
package.json
packages/webcomponents/src/api/TerminalOrder.ts
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list-core.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list-filters.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list-params-state.ts
packages/webcomponents/src/styles/parts.ts
packages/webcomponents/src/ui-components/filters/readme.md

- Adds `terminal-orders-list-filters` component which can be optionally rendered alongside `terminal-orders-list` to filter via status or order type
- includes CSS parts for the menu and its corresponding inputs
- query params can be passed to the filter menu as props
- Adds new example file rendering the list and the filters together: `pnpm dev:terminal-orders-list-with-filters`
Links
-----
Closes #890 
--------------
- On any task
- [] Perform dev QA on Chrome, Firefox, and Safari
To test, please run `pnpm dev:terminal-orders-list-with-filters`
Passing in props to filter component:

Add `terminal-orders-list-filters` component

---

packages/webcomponents/src/api/Api.ts
packages/webcomponents/src/api/TerminalOrder.ts
packages/webcomponents/src/api/services/terminal.service.ts
packages/webcomponents/src/components/order-terminals/order-terminals.tsx

This PR commits the following: 
- Rename `account_id` to `sub_account_id` on the Order Terminals payload post request to match recent API changes.
- Refactor the API.post method to accept an additional `headers` argument.
- Send `sub-account` header in the Order Terminal post request to address an authorization issue. 
Links
-----
#937 
--------------
- On any task
- On bugs
Setup: Run `pnpm dev:order-terminals`.

Add headers support to API requests and rename account_id to sub_account_id in TerminalOrder

---

packages/webcomponents/src/components/terminal-orders-list/test/__snapshots__/terminal-orders-list-core.spec.tsx.snap
packages/webcomponents/src/components/terminal-orders-list/test/get-terminal-orders.spec.tsx
packages/webcomponents/src/components/terminal-orders-list/test/terminal-orders-list-core.spec.tsx
packages/webcomponents/src/components/terminal-orders-list/test/terminal-orders-list-with-filters.spec.tsx
packages/webcomponents/src/components/terminal-orders-list/test/terminal-orders-list.spec.tsx

- Adds unit test coverage for terminal-orders-list and filters
Links
-----
Closes #935 
--------------
- On any task

`terminal-orders-list` Unit Tests

---

apps/docs/stories/components/TerminalOrdersList/Docs.mdx
apps/docs/stories/components/TerminalOrdersList/example.ts
apps/docs/stories/components/TerminalOrdersList/index.stories.tsx
apps/docs/stories/utils/mockAllServices.ts
mockData/mockTerminalOrdersListSuccess.json
packages/webcomponents/src/components/terminal-orders-list/test/__snapshots__/terminal-orders-list-core.spec.tsx.snap
packages/webcomponents/src/components/terminal-orders-list/test/terminal-orders-list-core.spec.tsx

- Adds page to Storybook showing documentation and example for `terminal-orders-list`
Links
-----
Closes #893 
--------------
- On any task

`terminal-orders-list` Documentation and Example

---

packages/webcomponents/src/actions/business/get-business.ts
packages/webcomponents/src/actions/terminal/get-terminal-models.ts
packages/webcomponents/src/actions/terminal/order-terminals.ts
packages/webcomponents/src/api/services/business.service.ts
packages/webcomponents/src/components/order-terminals/order-terminals.tsx

Likewise other components, the optional `apiOrigin` prop is needed so we can use a different API on the dashboard.
Links
-----
#956 
--------------
- On any task
- On bugs
Setup: 
- `pnpm dev:order-terminals`.
- Add `api-origin` prop in the component `apps/component-examples/examples/order-terminals.js`.

Add apiOrigin parameter to business and terminal service methods

---

.changeset/witty-coins-grow.md
apps/component-examples/examples/terminals-list.js
packages/webcomponents/src/api/Terminal.ts
packages/webcomponents/src/components/terminals-list/terminals-table.tsx
packages/webcomponents/src/utils/utils.ts

- Uses `TerminalModels` enum in `Terminal` class and captures new property `model_name` in class instantiation
- Uses `TerminalProviders` enum in `Terminal` class for `provider` property
- Adds new optional columns to `terminals-list`: 
- `model_name` - shows `model_name` property in new column
- `id` shows `id` property in new column
- `provider` shows `provider` property in new column
Links
-----
Closes #954 
--------------
- On any task

Add new optional columns for `justifi-terminals-list`

---

.changeset/strange-lobsters-roll.md
apps/component-examples/examples/order-terminals.js
packages/webcomponents/src/components/order-terminals/order-terminals.tsx
packages/webcomponents/src/components/order-terminals/test/__snapshots__/order-terminals.spec.tsx.snap

Remove the error state in favor of using the error-event.
Links
-----
--------------
- On any task
- On bugs
`pnpm dev:order-terminals`

Remove unused error rendering logic from OrderTerminals component

---

.changeset/smooth-boats-obey.md
packages/webcomponents/src/components/order-terminals/order-terminals.tsx
packages/webcomponents/src/components/order-terminals/test/__snapshots__/order-terminals.spec.tsx.snap
packages/webcomponents/src/utils/utils.ts

This PR commits the following changes: 
- Add back the "Shipping Address" information in case `shipping={true}`.
- Adds a helper function to format phone numbers and use it to format the "Representative Details" phone number on the order terminals component.
Type of Change
--------------
Links
-----
#536
UX Review
---------
If your changes impact the user experience, check these considerations and send to UX for review, prior to QA.
Run`pnpm dev:order-terminals`.

960 justifi order terminals add shipping address mistakenly removed

---

.changeset/twelve-cobras-eat.md
packages/webcomponents/src/components/order-terminals/order-terminals.tsx
packages/webcomponents/src/components/order-terminals/test/__snapshots__/order-terminals.spec.tsx.snap

**This PR commits the following**
Links
-----
#968 
--------------
- On any task
- On bugs
Run `pnpm dev:order-terminals`.

Add customizable submit button text and improve address header display in OrderTerminals component

---

.changeset/lemon-students-unite.md
packages/webcomponents/src/api/TerminalOrder.ts
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-table.tsx

- Updates terminal order class with `company_name` - new property from backend
- Adds optional column: `company_name` to `terminal-orders-list`
Links
-----
Closes #970 
To test this - run `pnpm dev:terminal-orders-list`
You will need to edit the columns prop for the component in the example file. You may copy and paste this as an example:
`columns="company_name,created_at,updated_at,order_status,quantity"`

Add `company_name` column terminal orders list

---

.changeset/green-cows-tickle.md
packages/webcomponents/src/components/order-terminals/order-terminals.tsx
packages/webcomponents/src/components/terminals-list/terminals-table.tsx

The way the Business Details header was being set was buggy, for some reason, passing shipping=true was being evaluated as false.
In the example files it was working though, this was maybe a re-render issue.
`addressHeader = this.shipping ? "Shipping Address:" : "Business Address:";`
Links
-----
Closes #977 
Closes #980 
--------------
- On any task
- On bugs
1 - Open the terminal in `web-component-library/packages/webcomponents` and run `pnpm link --global`.
2 - Go to the root folder and run `pnpm dev`.
3 - Open the terminal in `customer-admin-fe` and run `pnpm link --global @justifi/webcomponents`.
4 - Run ` pnpm build && pnpm start`.
5 - Put a console.log inside `componentWillLoad` on …

Refactor address header logic in OrderTerminals component

---

packages/webcomponents/src/api/Api.ts
packages/webcomponents/src/api/services/analytics.service.ts
packages/webcomponents/src/api/services/business.service.ts
packages/webcomponents/src/api/services/checkout.service.ts
packages/webcomponents/src/api/services/dispute.service.ts
packages/webcomponents/src/api/services/insurance.service.ts
packages/webcomponents/src/api/services/payment.service.ts
packages/webcomponents/src/api/services/payout.service.ts
packages/webcomponents/src/api/services/provision.service.ts
packages/webcomponents/src/api/services/reports.service.ts
packages/webcomponents/src/api/services/subaccounts.service.ts
packages/webcomponents/src/api/services/terminal.service.ts
packages/webcomponents/src/api/services/terminal_orders.service.ts
packages/webcomponents/src/components/business-forms/payment-provisioning/terms-and-conditions/business-terms-conditions-form-step.tsx

Like it was done in the `customer-admin-fe`, the `Api` class could be refactored to accept an object argument instead of each argument separated.
This improves clarity and maintenance.
Links
-----
#949 
--------------
- On any task
- On bugs
I couldn't run myself (even in main branch) the following examples: checkout, checkout-with-insurance and tokenize-payment-method.

Refactor API service calls to use object for parameters

---

.github/dependabot.yml

Change package ecosystem on `dependabot.yml`.
Value is supposed to be the ecosystem, not the tool.
Acceptable values: `npm, bundler, composer, devcontainers, dotnet-sdk, maven, mix, cargo, gradle, nuget, gomod, docker, docker-compose, elm, gitsubmodule, github-actions, pip, terraform, pub, swift, bun, uv, helm`
Links
-----
--------------
- On any task
- On bugs

Update dependabot configuration to use npm instead of pnpm

---

.changeset/whole-flies-deny.md
packages/webcomponents/src/styles/parts.ts
packages/webcomponents/src/ui-components/form/test/__snapshots__/form-control-checkbox.spec.tsx.snap

When setting `background: transparent` using the `background` part, the checkbox starts presenting a weird style not being possible to recognize it's current state. 
(checked)
This only happens when the `inputCheckbox`, `inputCheckboxInvalid`, `inputCheckboxFocused`, `inputCheckboxChecked`, `inputCheckboxCheckedFocused` parts are not set. 
The checkbox, however, still works, only the styles are affected. 
**Solution**
Removing the `background` part from the `inputCheckbox` composition seems to solve the problem. 
Links
-----
https://github.com/justifi-tech/engineering-artifacts/issues/137
--------------
- On any task
- On bugs
Setup: 
1 - On `apps/component-examples/css/theme.css`, remove …

137 storybooks docs stying example breaks checkbox

---

.changeset/deep-peaches-divide.md
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-table.tsx

- If showing `order_type` column in `terminal-orders-list`, value will be converted from snake_case to readable. `boarding_only` will now display as `Boarding Only`, and `boarding_shipping` will now display as `Boarding & Shipping`
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/141
1. in `terminal-orders-list.js` use the `columns` prop on the component to show `order_type` Example: `columns='created_at,updated_at,order_status,order_type,quantity'`
2. Run `pnpm build && pnpm dev:terminal-orders-list`

`terminal-orders-list`: Show `order_type` in readable format

---

.changeset/clever-ghosts-take.md
apps/component-examples/css/theme.css
apps/docs/stories/themes/dark.ts
apps/docs/stories/themes/light.ts
packages/webcomponents/src/components/business-forms/payment-provisioning/form-control-monetary-provisioning.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/test/__snapshots__/form-control-monetary-provisioning.spec.tsx.snap
packages/webcomponents/src/styles/parts.ts
packages/webcomponents/src/ui-components/form/form-control-monetary.tsx
packages/webcomponents/src/ui-components/form/test/__snapshots__/form-control-monetary.spec.tsx.snap

- Adds new part for input adornment shown with `form-control-monetary`
- Updates theme.css to add simple styling to the input adornment 
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/142

Add CSS part for $ input adornment

---

apps/docs/stories/components/TerminalOrdersList/Docs.mdx
apps/docs/stories/components/TerminalOrdersList/example.ts
apps/docs/stories/components/TerminalOrdersList/index.stories.tsx

This PR adds back the docs for `terminal-orders-list`
This work had already been approved before - but was removed due to the API not being ready at the time. 
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/140

Re-implement `terminal-orders-list` docs to storybook

---

.changeset/lovely-rabbits-call.md
apps/component-examples/css/example.css
apps/component-examples/examples/refund-payment.js
apps/docs/stories/components/RefundPayment/Docs.mdx
apps/docs/stories/components/RefundPayment/example.ts
apps/docs/stories/components/RefundPayment/index.stories.tsx
apps/docs/stories/utils/mockAllServices.ts
mockData/mockPostRefundSuccess.json
packages/webcomponents/src/components/refund-payment/refund-payment.tsx

- Adds documentation files for `justifi-refund-payment` component to Storybook
- Renames component method `handleSubmit` => `refundPayment`
- Improves example file by showing event usage, rendering output column on page, showing method usage
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/64
--------------
- On any task
General:
Storybook: 
`pnpm dev`
Component Example
`pnpm dev:refund-payment`

`justifi-refund-payment` - Storybook Docs and Example File Improvements

---

.changeset/fruity-socks-smell.md
mockData/mockTerminalOrdersListSuccess.json
packages/webcomponents/src/api/TerminalOrder.ts
packages/webcomponents/src/components/terminal-orders-list/terminal-order-status.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list-filters.tsx
packages/webcomponents/src/components/terminal-orders-list/test/__snapshots__/terminal-orders-list-core.spec.tsx.snap

- Adds support for new terminal order statuses:  `in_progress`, `on_hold`, `cancelled`
- Adds options to filter component's status input to show new statuses
- Adds badge mapping for new statuses to display on terminal-orders-list
- Updates mock data to add new orders showing new statuses
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/161
This one will be easiest to test by quickly loading storybook which will show the component with mock data

Add new terminal order statuses

---

packages/webcomponents/src/components/terminal-orders-list/terminal-order-status.tsx
packages/webcomponents/src/components/terminal-orders-list/test/__snapshots__/terminal-orders-list-core.spec.tsx.snap

This PR updates the status badge color on terminal orders with `in_progress` status. Updating the status badge to be the `primary` bootstrap badge

Terminal Orders: Update in_progress status badge color to primary

---

apps/component-examples/examples/modular-checkout.js
packages/webcomponents/src/components/checkout-wrapper/checkout-wrapper.tsx
packages/webcomponents/src/components/modular-checkout-parts/card-form-skeleton.tsx
packages/webcomponents/src/components/modular-checkout-parts/card-form.tsx
packages/webcomponents/src/store/checkout.store.ts
packages/webcomponents/src/ui-components/form/readme.md

**This PR includes the following changes:**
* Adds the new `justifi-card-form` component to the `modular-checkout-parts` folder.
* Copies `card-form-skeleton` into the `modular-checkout-parts` folder.
* Updates `checkout-wrapper` → `tokenizePaymentMethod`: adds an `addressPostalCode` argument to handle cases where the user doesn’t include the `postal-code` component.
**Key differences between the new CardForm and the old one:**
* The new version uses Shadow DOM, `StyledHost`, and `hidden-input` to support styling, as the checkout wrapper doesn’t use Shadow DOM.
* It sets a default value for the `iframeOrigin` prop.
* It initializes `checkPkgVersion` and `analytics`.
Links
-----
https://github.com/justifi-tech/engineering-artifacts/issues/100
--------------
- On …

Add JustifiCardForm and CardFormSkeleton components

---

packages/webcomponents/src/actions/payout/get-payout-details.ts
packages/webcomponents/src/components/payout-details/payout-details.tsx
packages/webcomponents/src/components/payout-details/test/get-payout-details.spec.ts
packages/webcomponents/src/components/payout-details/test/payout-details-core.spec.tsx

This PR passes the `api-origin` prop from the component to the underlying api request handlers
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/276
Run `pnpm dev:payout-details` example to test. Update example file to modify `api-origin` prop on the component.

`payout-details`: Pass api-origin prop to payout GET request

---

apps/docs/stories/components/DisputeManagement/Docs.mdx

**Summary**
Fixes Authorization instructions for the Dispute Management component: 
`read:dispute:account_id` ❌
`read:dispute:dispute_id` ✅
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/293

Fix role references in authorization section of Dispute Management documentaion

---

packages/webcomponents/src/actions/payout/get-payout-details.ts
packages/webcomponents/src/actions/payout/get-payout-transactions.ts
packages/webcomponents/src/actions/payout/get-payouts.ts
packages/webcomponents/src/actions/sub-account/get-subaccounts.ts
packages/webcomponents/src/api/ApiNew.ts
packages/webcomponents/src/api/services/payout.service.ts
packages/webcomponents/src/api/services/subaccounts.service.ts
packages/webcomponents/src/components/checkouts-list/checkouts-list.tsx
packages/webcomponents/src/components/checkouts-list/test/checkouts-list-core.spec.tsx
packages/webcomponents/src/components/config-provider/config-provider.tsx
packages/webcomponents/src/components/config-provider/config-state.ts
packages/webcomponents/src/components/payout-details/get-payout-csv.ts
packages/webcomponents/src/components/payout-details/payout-details.tsx
packages/webcomponents/src/components/payout-details/test/get-payout-details.spec.ts
packages/webcomponents/src/components/payout-details/test/payout-details-core.spec.tsx
packages/webcomponents/src/components/payout-transactions-list/payout-transactions-list.tsx
packages/webcomponents/src/components/payouts-list/payouts-list.tsx
packages/webcomponents/src/components/payouts-list/test/get-payouts.spec.ts
packages/webcomponents/src/components/payouts-list/test/payouts-list-core.spec.tsx
packages/webcomponents/src/components/terminals-list/terminals-list.tsx
packages/webcomponents/src/components/terminals-list/test/terminals-list-core.spec.tsx

- Adds new component for internal use in our dashboard: `justifi-config-provider` which will handle passing certain values to components in the dashboard without the need to write hidden / undocumented props. 
- Creates new `ApiNew.ts` file which is almost an exact copy of the existing Api.ts file - but only requires authToken as a prop when initializing Api() and grabs `apiOrigin` from `config-state` by default. 
- Refactors payout related components: `payouts-list`, `payout-details`, and `payout-transactions-list` to no longer accept `apiOrigin` prop. 
- Refactors `subaccounts` api requests (used in payouts-list, terminals-list, checkouts-list) to use new ApiNew.ts file
- Note: this was just easiest to go ahead and do this as well since payouts-list needs …

Internal Component: `justifi-config-provider` for dashboard use

---

packages/webcomponents/src/actions/payment/get-payment-details.ts
packages/webcomponents/src/actions/payment/get-payment-transactions.ts
packages/webcomponents/src/actions/payment/get-payments.ts
packages/webcomponents/src/actions/refund/refund-actions.ts
packages/webcomponents/src/api/services/payment.service.ts
packages/webcomponents/src/api/services/payout.service.ts
packages/webcomponents/src/api/services/refund.service.ts
packages/webcomponents/src/components/payment-details/payment-details.tsx
packages/webcomponents/src/components/payment-details/test/get-payment-details.spec.ts
packages/webcomponents/src/components/payment-details/test/payment-details-core.spec.tsx
packages/webcomponents/src/components/payment-transactions-list/payment-transactions-list.tsx
packages/webcomponents/src/components/payments-list/payments-list.tsx
packages/webcomponents/src/components/payments-list/test/get-payments.spec.ts
packages/webcomponents/src/components/payments-list/test/payments-list-core.spec.tsx
packages/webcomponents/src/components/refund-payment/refund-payment.tsx

- removes `apiOrigin` prop from the following components: `payments-list`, `payment-details`, `payment-transactions-list`, `refund-payment`
- Updates service and api files
- Updates broken test files
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/316
--------------
- On any task
In order to test the config-provider - you'll need to render it anywhere in the payment example files. We're going to test all 3 payment components and the refund component to verify correct behavior. 
`payments-list`
`payment-details`
`payment-transactions-list`
`refund-payment`

Remove `apiOrigin` prop from Payment related components

---

packages/webcomponents/src/actions/business/get-business.ts
packages/webcomponents/src/actions/terminal/get-terminal-models.ts
packages/webcomponents/src/actions/terminal/get-terminal-orders.ts
packages/webcomponents/src/actions/terminal/get-terminals.ts
packages/webcomponents/src/api/services/business.service.ts
packages/webcomponents/src/api/services/terminal.service.ts
packages/webcomponents/src/api/services/terminal_orders.service.ts
packages/webcomponents/src/components/order-terminals/order-terminals.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list.tsx
packages/webcomponents/src/components/terminal-orders-list/test/get-terminal-orders.spec.tsx
packages/webcomponents/src/components/terminal-orders-list/test/terminal-orders-list-core.spec.tsx
packages/webcomponents/src/components/terminals-list/terminals-list.tsx
packages/webcomponents/src/components/terminals-list/test/get-terminals.spec.tsx
packages/webcomponents/src/components/terminals-list/test/terminals-list-core.spec.tsx

- removes `apiOrigin` prop from the following components: `terminals-list`, `terminal-orders-list`, `order-terminals`
- Updates service and api files
- Updates broken test files
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/328
--------------
- On any task
In order to test the config-provider - you'll need to render it anywhere in the payment example files. We're going to test all 3 payment components and the refund component to verify correct behavior. 
`terminals-list`
`terminal-orders-list`
`order-terminals`

Remove `apiOrigin` prop from Terminal related components

---

.changeset/spotty-lands-ring.md
packages/webcomponents/src/components/business-forms/payment-provisioning/business-core-info/business-core-info-form-step-core.tsx
packages/webcomponents/src/components/business-forms/schemas/business-core-info-schema.ts

This PR commits the following changes to the first step of  `payment-provisioning`:
- Updates help text for `tax_id` field to add in new sentence: `Enter value without dashes.`
- Updates error text for `tax_id` field to be: `Enter valid tax id (SSN or EIN) without dashes`
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/334
--------------
- On any task

`PaymentProvisioning`: add clearer error message for `tax_id` field

---

packages/webcomponents/src/components/checkout-wrapper/checkout-wrapper.tsx
packages/webcomponents/src/components/modular-checkout-parts/summary.tsx
packages/webcomponents/src/store/checkout.store.ts

**This PR commits the following changes**
* Adds the new component `justifi-checkout-summary` to be used with `justifi-checkout-wrapper`.
* Enhances `checkoutStore` with checkout data necessary for the Summary.
Links
-----
https://github.com/justifi-tech/engineering-artifacts/issues/74
--------------
- On any task
- On bugs
To test the new bank account component in a real-world setup, follow the steps below:
**Local Setup:**
1  - **Run iframe components locally**
* Navigate to `iframe-components`.
* Run: `npm run build` && `npm run dev`.
* This should start the server on `localhost:3003` and avoid `Not Authorized` errors during `payment-methods` API calls.
2  - **Configure environment for web component …

Implement checkout summary component and enhance checkout store with payment details

---

apps/docs/stories/components/BusinessDetails/example.ts
apps/docs/stories/components/BusinessForm/example.ts
apps/docs/stories/components/Checkout/example.ts
apps/docs/stories/components/CheckoutsList/example.ts
apps/docs/stories/components/DisputeManagement/example.ts
apps/docs/stories/components/GrossPaymentChart/example.ts
apps/docs/stories/components/PaymentDetails/example.ts
apps/docs/stories/components/PaymentProvisioning/example.ts
apps/docs/stories/components/PaymentsList/example.ts
apps/docs/stories/components/PayoutDetails/example.ts
apps/docs/stories/components/PayoutsList/example.ts
apps/docs/stories/components/TerminalOrdersList/example.ts
apps/docs/stories/components/TerminalsList/example.ts
apps/docs/stories/components/TokenizePaymentMethod/example.ts

- Updates several example files to use consistent syntax in regards to showing props in `kebab-case` and using self-closing component tags
- Changes props in example files that were written as `business-id="businessId"` => `business-id="biz_123"`. Using actual ID prefixes in example files now. 
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/312

Component Docs: Consistent component example syntax

---

.changeset/gentle-poems-slide.md
mockData/mockPayoutDetailsSuccess.json
packages/webcomponents/src/components/payment-details/payment-details-core.tsx
packages/webcomponents/src/components/payment-details/test/__snapshots__/payment-details-core.spec.tsx.snap
packages/webcomponents/src/components/payout-details/payout-details-core.tsx
packages/webcomponents/src/components/payout-details/test/__snapshots__/payout-details-core.spec.tsx.snap
pnpm-lock.yaml

- Hides metadata section on payment and payout detail components if metadata is null or falsy
- Updates snapshots
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/374
--------------
- On any task

`payment-details` and `payout-details`: conditionally render Metadata section

---

packages/webcomponents/src/actions/checkout/get-checkouts.ts
packages/webcomponents/src/actions/dispute/dispute-actions.ts
packages/webcomponents/src/api/ApiNew.ts
packages/webcomponents/src/api/services/analytics.service.ts
packages/webcomponents/src/api/services/checkout.service.ts
packages/webcomponents/src/api/services/dispute.service.ts
packages/webcomponents/src/components/checkout/bank-account-form/bank-account-form.tsx
packages/webcomponents/src/components/checkout/card-form/card-form.tsx
packages/webcomponents/src/components/checkout/checkout-core.tsx
packages/webcomponents/src/components/checkout/checkout.tsx
packages/webcomponents/src/components/checkout/new-payment-method.tsx
packages/webcomponents/src/components/checkout/payment-method-options.tsx
packages/webcomponents/src/components/checkout/test/__snapshots__/checkout.spec.tsx.snap
packages/webcomponents/src/components/checkouts-list/checkouts-list.tsx
packages/webcomponents/src/components/checkouts-list/test/checkouts-list-core.spec.tsx
packages/webcomponents/src/components/checkouts-list/test/get-checkouts.spec.ts
packages/webcomponents/src/components/config-provider/config-provider.tsx
packages/webcomponents/src/components/config-provider/config-state.ts
packages/webcomponents/src/components/dispute-management/dispute-management.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/dispute-response-actions.ts
packages/webcomponents/src/components/tokenize-payment-method/tokenize-payment-method.tsx

- removes `apiOrigin` prop from the following components: `checkouts-list`, `dispute`. Now uses new api file which awaits config provider to determine api-origin used for requests.
- Removes `iframeOrigin` prop from `tokenize-payment-method`. Now waits for config-provider before using provided iframe value or falling back to default value in env variables
- Updates service and api files for checkouts and disputes.
- Updates broken test files
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/336
--------------
- On any task
In order to test the config-provider - you'll need to render it anywhere in the payment example files. We're going to test all 3 payment …

Implement `config-state` to `tokenize-payment`, `checkouts-list`, `dispute`,  and `analytics`

---

apps/component-examples/examples/business-details.js
apps/component-examples/examples/business-form.js
apps/component-examples/package.json
package.json
packages/webcomponents/src/api/services/business.service.ts
packages/webcomponents/src/api/services/provision.service.ts
packages/webcomponents/src/components/business-forms/business-form/business-form.tsx
packages/webcomponents/src/components/business-forms/business-form/readme.md
packages/webcomponents/src/components/business-forms/business-form/test/business-form.spec.tsx

- Uses new api file `ApiNew.ts` to form api requests in business components - `business-form`, `business-details`, `payment-provisioning`
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/343
--------------
- On any task
In order to test the config-provider - you'll need to render it anywhere in the example files. We're going to test all 3 business components to verify correct behavior. 
`business-form`
`business-details`
`payment-provisioning`

Implement `config-state` to Business related components

---

.changeset/lucky-hats-live.md
packages/webcomponents/src/api/Analytics.ts
packages/webcomponents/src/components/business-details/business-details.tsx
packages/webcomponents/src/components/business-forms/business-form/business-form.tsx
packages/webcomponents/src/components/business-forms/payment-provisioning/payment-provisioning.tsx
packages/webcomponents/src/components/checkout/checkout.tsx
packages/webcomponents/src/components/checkouts-list/checkouts-list.tsx
packages/webcomponents/src/components/dispute-management/dispute-management.tsx
packages/webcomponents/src/components/dispute-management/dispute-response/dispute-response.tsx
packages/webcomponents/src/components/gross-payment-chart/gross-payment-chart.tsx
packages/webcomponents/src/components/insurance/season-interruption/season-interruption-insurance.tsx
packages/webcomponents/src/components/order-terminals/order-terminals.tsx
packages/webcomponents/src/components/payment-details/payment-details.tsx
packages/webcomponents/src/components/payment-transactions-list/payment-transactions-list.tsx
packages/webcomponents/src/components/payments-list/payments-list.tsx
packages/webcomponents/src/components/payout-details/payout-details.tsx
packages/webcomponents/src/components/payout-transactions-list/payout-transactions-list.tsx
packages/webcomponents/src/components/payouts-list/payouts-list.tsx
packages/webcomponents/src/components/terminal-orders-list/terminal-orders-list.tsx
packages/webcomponents/src/components/terminals-list/terminals-list.tsx
packages/webcomponents/src/components/tokenize-payment-method/tokenize-payment-method.tsx
pnpm-lock.yaml

This PR prevents the analytics cleanup function from causing errors if it doesn't detect any event listeners.
Links
-----
Closes https://github.com/justifi-tech/engineering-artifacts/issues/236
--------------
- On any task
The best way to test this is to link local web components to the local dashboard using `pnpm link`
Build and link the web component library package.
- Run: `pnpm build && pnpm dev`.
- Then: `cd packages/webcomponents && pnpm link --global`.
Link dashboard - from the dashboard root directory run `pnpm link @justifi/webcomponents`
Open the browser dev console, and navigate to and from pages that contain web components, IE payments view, payouts view, terminals view, etc

Fix Analytics Cleanup error

---

apps/docs/stories/components/ModularCheckout/Docs.mdx

Slightly updates the `Providing Billing Information` section in `apps/docs/stories/components/ModularCheckout/Docs.mdx`:
- adds index links to card billing and bank account billing
- Helps make this section more readable by explicitly listing ways that billing info can be provided for both card form and bank form payments

Index Links for card-form billing and bank-account-form billing

---

packages/webcomponents/src/ui-components/index.ts
packages/webcomponents/src/ui-components/shadow-dom-components/justifi-radio-list-item.tsx

- Add new shadow DOM component for radio list items
- Export component from ui-components index
- Provides reusable radio button functionality with proper styling
Links
-----
--------------
- On any task
- On bugs
Component to be used in a subsequent PR which will receive QA. The component is not actually used in this PR, so there is no manual testing to be done

feat: Add JustifiRadioListItem shadow DOM component

---

.github/workflows/publish-rc.yml

This will prevent RC versions to be downloaded when `npm install @justifi/webcomponents` is run without a specified version. 
**Key Changes for Release Candidates:**
1 - Workflow Name: "Publish Release Candidate Components" to clearly distinguish it
2 - Job Name: "Build RC" for clarity
3 - Versioning: Uses pnpm version-packages --preid rc to create pre-release versions (e.g., 1.0.0-rc.1)
4 - NPM Tag: Uses pnpm release --tag next to publish with the next tag instead of latest
**How it works:**
* Manual Trigger: Like your main workflow, this runs on workflow_dispatch so you can manually trigger it when you want to publish an RC
* Pre-release Versioning: The --preid rc flag creates version numbers like 1.0.0-rc.1, 1.0.0-rc.2, etc.
* Next Tag: Packages are published with the next tag, so …

Add GitHub Actions workflow for publishing release candidate components

---

.changeset/proud-nails-open.md
apps/component-examples/CHANGELOG.md
apps/component-examples/package.json
apps/docs/CHANGELOG.md
apps/docs/package.json
packages/webcomponents/CHANGELOG.md
packages/webcomponents/package.json
packages/webcomponents/src/components/checkout/bank-account-form/bank-account-form.tsx
packages/webcomponents/src/components/checkout/card-form/card-form.tsx
packages/webcomponents/src/utils/utils.ts

Links
-----
https://github.com/justifi-tech/engineering-artifacts/issues/871
--------------
- On any task
- On bugs
Setup: `iframe-components` should be run locally from the `597-tokenize-payment-method-web-component-not-sending-all-values` branch.
This can be tested by opening a checkout in two different tabs. 
**Backward compatibility**
Run `web-component-library` from the `main` branch, and run `iframe-components` from the `597-tokenize-payment-method-web-component-not-sending-all-values`

871 fix card formbank account form share tabid to the iframes to prevent cross tab iframe communication

---

.changeset/loud-flowers-mix.md
.changeset/thick-bananas-trade.md
apps/docs/stories/components/ModularCheckout/Docs.mdx
apps/docs/stories/components/ModularCheckout/introduction.mdx
packages/webcomponents/package.json
packages/webcomponents/src/api/services/apple-pay.service.ts
packages/webcomponents/src/components/modular-checkout/modular-checkout.tsx

This pull request focuses on improving the `justifi-modular-checkout` component in `@justifi/webcomponents` by preventing checkout submission without a selected payment method and clarifying related documentation. It also includes a minor bug fix and updates the package version.
**Checkout validation and error handling:**
* Prevents the checkout from being submitted if no payment method is selected, and emits an error event if this occurs (`modular-checkout.tsx`).
* Updates the changelog to reflect this validation fix.
**Documentation updates:**
* Clarifies in the docs that no default payment method is selected automatically, and developers must explicitly set a default using `setSelectedPaymentMethod`. [[1]](diffhunk://#diff-59418e837565890ef98a44755d3f9f20159c2f558da65c94196026ddc68f992d …

Fix no selected payment method
